### PR TITLE
Issue 1398

### LINKED ISSUE #1398: Add a winter kit (cowl grill), expand icing effects
Today I was flying around in the rocky mountains and I faced a comical problem, the plane engine is unable to keep a decent temperature. Normally this wouldn‘t be a problem within the simulation, however my engine died on landing and I could not get it started to clear the runway until I used the external heat. Normally in real life, cowl blocks would be used to reduce the amount of air flowing through the engines to allow them to stay warm. I think that It would be a good option to add Cowl Blocks somewhere in the aircraft options menu.

### PR DESCRIPTION
**Pull request by wlbragg**
Fixes #1398 

@dany93 
Ready for testing. I am guessing at the cooling effect. I noticed the c182 cut in half their default cooling value when applying their winter kit. So I did about the same. Ours defaults to .514, I set it to .25 when the cowl grill is inplace. A total guess on my part. I watched the oil tempf property when testing.

There is no checks performed yet to allow for activation, like allowing only when stationary or prop not running. I left it open for testing. Also no check for conflicts with other equipment like he cowl plugs. I finish all that up once we happy with the numbers.

I added, but did not activate the c182 pitot and static port icing and the cowling air flow icing. I wanted to finish the cowl grill numbers completely before adding the rest of it.

If you have time and are interested, feel free to look at the numbers for all of it and test and offer recommendations.

### CODE REVIEW

**Comment by dany93** [comment]
@wlbragg 
- 1- **Cowl grill and plugs**
You wrote
>There is no checks performed yet to allow for activation, like allowing only when stationary or prop not running

But apparently from my tests, BATT, ALT and Magnetos, all = 0, are needed conditions, checked. Which is fine IMO.
(I could not find where it was written in the files)

- 2- **Icing pointmass**
icing.xml
```
<system name="icing">
   (....)
            <output>inertia/pointmass-weight-lbs[6]</output>
```
In c172p.xml, `pointmass-weight-lbs[6]` is `<pointmass name="Right bush wheel 26 inches">`

Still c172p.xml, `pointmass [17]` I guess,
```
        <pointmass name="Ice">
           <weight unit="LBS"> 0 </weight>
            <location name="POINTMASS" unit="IN">
            <x>307.78 </x>
            <y> 0 </y>
            <z>56.9 </z>
            </location>
        </pointmass>

```
X and Z do not match the c172p coordinates for a single pointmass.

**Comment by wlbragg** [comment]
Ah, good catch. I didn't notice that.

I think the 307.78 was supposed to be 30.78 but the 56.9 is suspect.

Speaking of pointmass's, the following looks inconsistent, shouldn't engine weight and oil weight basically be the same point? If so we could possible combine them?
~~~
<!-- Extra weight for the aircraft with 180 hp engine, **Basic empty** (= with full oil), pointmass [15]; managed by Systems/bushkit.xml -->
        <!-- for empty aircraft CG at x = 38.12 ins, from Cessna 172S - N552SP POH (1998) p.6-12, Weight and moment tabulation: 1642 lbs, 62600 lb-ins -->
        <pointmass name="extra weight 180hp">
            <weight unit="LBS"> 0 </weight>
            <location name="POINTMASS" unit="IN">
                <x> 30.29 </x>
                <y>  0 </y>
                <z> 26.6 </z>
            </location>
        </pointmass>

        <!-- Loss of weight due to lacking oil, pointmass [16]. engine.nas, c172p-engine.xml -->
        <pointmass name="lacking oil weight">
            <weight unit="LBS"> 0 </weight>
            <location name="POINTMASS" unit="IN">
                <x> -19.7 </x>
                <y> 0 </y>
                <z> 26.6 </z>
            </location>
        </pointmass>
~~~

**Comment by dany93** [comment]
@wlbragg wrote
>Speaking of pointmass's, the following looks inconsistent, shouldn't engine weight and oil weight basically be the same point? If so we could possible combine them?

I had the same interrogation some days ago, at reading this part probably for the same reason as you.
I should elaborate (I will try to), I don't know how without being too long.
X = 30.29 is not the 180 hp engine location. Its location can be guessed to be about the same as the 160 hp one.

The extra weight for the 180 hp aircraft as a whole is 1642 - 1467 lbs  = 175 lbs
At first view, it might be taken into account merely by adding this weight difference at the engine location, but the engine is not the main contributor.
IO-320 engine : weight about 277 lb (depend on model)
IO-360 engine : weight about 300 lb (depend on model)
Difference due to engine 300 - 277 = 23 lb (about)

**The POH mass and balance of each aircraft (taken as a whole) is the reference**.
The extra weight location must be calculated with the following data ("Basic empty" aircraft):
- c172 with IO-320 (160 hp): weight 1467 lbs, moment 57300 lbs-ins (giving CoG at X = 39.05 ins)
- c172 with IO-360 (180 hp): weight 1642 lbs, moment 62600 lbs-ins (giving CoG at X = 38.12 ins)

The "moment" in POHs is `weight * CoG_arm` where CoG_arm is the distance between DATUM and CoG.

c172 with IO-320 : moment = 57300 lbs-ins
c172 with IO-360 (175 lbs added at arm = X) : `moment = 57300 + 175 * X = 62600`
Which gives `X = (62600 - 57300) / 175 = 30.29 ins`
We can check in the simulator that it gives the CoG at 38.12 ins for the c172 with 180 hp (at "Basic empty" weight).
____________________________________________

Perhaps it might has been done more clearly by managing it in Systems, as you did for the gears (Z values).  But I did it like this because I didn't know (I still don't know) how to change the empty weight and CoG location in-sim. I had to enter _values_ in the FDM file, not properties.

**Comment by wlbragg** [comment]
175 VS 23 spread out across the airframe
OK, makes sense, thanks.

I was starting to look closer at the weight being added by ice accumulation. Checking the numbers and verifying if they seem reasonable. It dawned on me that the ice accumulation seed number (the first value associated with ice accumulating on a surface) is actually broken down by which surface it is collecting on.

Wing  = /fdm/jsbsim/ice/wing
Fuselage = /fdm/jsbsim/ice/fuselage
Propeller = /fdm/jsbsim/ice/proppeler
Windshield = /fdm/jsbsim/ice/windshield
Stabilizer = /fdm/jsbsim/ice/stabilizer (this should probably split to Elevator and Stabilizer)

The other locations are too small to really be of interest weight wise.

These locations are in completely different locations for the most part. We have a value for each ~which is then added altogether~ and converted to weight in c172p.nas, starting  at line 475...

~~~
var icinggraphic = func {
    var ice= getprop("/fdm/jsbsim/ice/wing") or 0;
    setprop("/fdm/jsbsim/ice/graphic", (ice *2.55));

	settimer(icinggraphic, 0.1);
}
icinggraphic();
~~~

I just noticed we are only using the wing value for graphics overall and weight. ThIs I will for sure change, at least the weight number. Maybe not the graphic masks, we'll see.

When I calculate the "multiple" weight numbers there is no reason not to break it out to the various locations.

I, or if you want a challenge, will research the weight of ice, surface area * weight of ice per measurement scale.

Also verify reasonable values of accumulation per mile which currently is
# none: sublimating 0.3" / 80NM
-0.3/80,

# traces: 0.5" / 80NM
0.5/80.0,

# light: 0.5" / 40NM
0.5/40.0,

# moderate: 0.5" / 20NM
0.5/20.0,

#severe: 0.5" / 10NM
 0.5/10

**Comment by wlbragg** [comment]
@dany93 
I am finished. I broke out the surface ice objects to their respective pointmass locations. I used the FDM-Datum-axes file to locate the points. Thanks you for that, it made it much easier.
I have been using the following helper to watch some of the properties, add it to the end of Nasal/c172p.nas if you want to monitor any properties for testing.
I also pushed the "c172p surface ice calulations.txt" file I used to calculate the weight of the surface ice accumulation. It's not perfect, but I think a reasonable guesstimate. It is based on 5 lbs of ice per sqft at 1" thick. I more or less calculated the areas you see the visual ice forming on. It definitely changes the COG as ice accumulates.

As far as I can tell it is ready to be merged. I am not planning on doing anything else regarding ice in the short term.

~~~
###############################################################################
# On-screen displays
var enableOSD = func {
    var left  = screen.display.new(20, 10);
    var right = screen.display.new(-300, 10);

    left.add("/fdm/jsbsim/ice/wing");
    left.add("/fdm/jsbsim/inertia/pointmass-weight-lbs[17]");
    left.add("/fdm/jsbsim/ice/elevator");
    left.add("/fdm/jsbsim/inertia/pointmass-weight-lbs[18]");
    left.add("/fdm/jsbsim/ice/stabilizer");
    left.add("/fdm/jsbsim/inertia/pointmass-weight-lbs[19]");
    left.add("/fdm/jsbsim/ice/fuselage");
    left.add("/fdm/jsbsim/inertia/pointmass-weight-lbs[20]");
    left.add("/fdm/jsbsim/ice/windshield");
    left.add("/fdm/jsbsim/inertia/pointmass-weight-lbs[21]");
    left.add("/fdm/jsbsim/ice/propeller");
    left.add("/fdm/jsbsim/inertia/pointmass-weight-lbs[22]");
    left.add("/fdm/jsbsim/ice/total-ice-lbs");
    left.add("/fdm/jsbsim/ice/graphic");

    right.add("/systems/static[0]/pressure-inhg");
    right.add("/systems/static[1]/pressure-inhg-venturi");
    right.add("/systems/static-pressure-inhg-selected");
}
enableOSD();
~~~

**Comment by dany93** [comment]
@wlbragg 
I've started observing, but I can't see anything wrong.
I'll try once or twice more before merging.

To your screen displays, I've added
```
    left.add("/position/altitude-ft"); 
    left.add("/velocities/airspeed-kt");     
    left.add("/environment/relative-humidity");     
    left.add("/environment/temperature-degc"); 
    left.add("/environment/icing/icing-factor");   
    left.add("/environment/icing/icing-severity");
```
_(Altitude and airspeed in the event of instrument failure due to icing)_

Amazing work!

**Comment by wlbragg** [comment]
There were a couple more bugs I found and fixed.

Save/Restore system was failing because the fg1000 variant properties were null when not using the fg1000 variant but trying to save its data. I put conditioned on what properties to save if the fg1000 wasn't loaded.

The AltStatic knob was out of position in the model and burying into the panel. I repositioned it.

Unless I find other bugs and push something else before you merge, I'm still done, ready to merge whenever your ready.

**Pull request merged**
