### PR TITLE
Allow default action in viewfrom in mouse manager

### LINKED ISSUE #1373: Mouse scroll to change zoom doesn't work anymore.
As the title says. You can no longer change FOV with the mouse wheel.

### PR DESCRIPTION
**Pull request by wlbragg**
Fixes #1373

Adds back in the default mouse action when in a viewfrom view mode.

@Megaf 
Please pull and test this.

@legoboyvdlp after @Megaf tests and confirms this works, would you mind testing what you can as far as normal views you use and if satisfied, merge and cherry pick again to 2020.3.
Thanks

### CODE REVIEW

**Comment by Megaf** [comment]
@wlbragg This fixes my reported issue yes. Now it is possible to control FOV/Zoom/Distance with right click + scroll.

BUT! It seems like "distance" is in use for all or at least most of the camera views, including tower views, should we open another issue for that?

**Comment by wlbragg** [comment]
>BUT! It seems like "distance" is in use for all or at least most of the camera views, including tower views, should we open another issue for that?

Oops hit a wrong button.
This is subjective and in my opinion requires some discussion. This view manager has been there for a long time with no complaints. About the time we change it then we will get complaints for that. As far as I know your the only one who brought up an issue with the manager and that issue is corrected now, without causing adverse side effects to the view manager. I'm not going to tell you not to make an issue, but I doubt I will be involved with it unless I am convinced of its merits.

**Comment by wlbragg** [comment]
@legoboyvdlp this is ready for a last test and if satisfied, merge and cherry pick again to 2020.3.

**Comment by legoboyvdlp** [comment]
@Megaf I don't know if I'm not seeing it or what but I'm not seeing that distance is in use for zoom in views. It still changes FOV for me (x / X keys). Which, is a good thing. Can you confirm?

I can't test this @wlbragg unfortunately as I have a touchpad; not a mouse. OK to just merge it?

**Comment by wlbragg** [comment]
Yeah, go ahead. I'm confident in what it does.

**Pull request merged**
