### PR TITLE
HOLD - Miscellaneous issues - HOLD

### LINKED ISSUE #724: Preflighting the C172 with outside view
So I took this for a test flight and preflight today. A few notes:
- The fuel tank quantity and sampling dialogs are neat. However the quantity could be also shown in liters in addition to gallons and pounds.
- Fuel sump clickpoint is a bit hard to find, maybe combine all fuel related stuff to one dialog and tie it to a big clickspot on the fuel tank itself? So that it shows quantity and lets you take the sample as well.
-  Is there a way to disable clicspots (and tooltips) from within the cockpit when you are in an outside view? There is a lot of stuff that is clickable and shows tooltips in the cockpit that gets in the way when you try to do a preflight check in an outside view. Same with outside clickspots when you are in the cockpi. I often accidentally clicked the engine oil clickspot when I used the GNS196.

### LINKED ISSUE #1180: Throttle lever does not move all the way in
This is the full throttle position with the new lever:

image

Throttle lever does not move all the way in. At full throttle the black part should be touching the back side, just like the mixture.

### PR DESCRIPTION
**Pull request by wlbragg**
Fixes cowl plugs strap to be over propeller.
Fixes #1180 
Fixes #724

I forgot to separately commit the throttle lever fix so there is no commit record for that, but it is included in this PR.

⚠️ ⚠️ ⚠️ ⚠️ ⚠️ ⚠️  DO NOT MERGE ⚠️ ⚠️ ⚠️ ⚠️ ⚠️ ⚠️

### CODE REVIEW

**Comment by dany93** [comment]
Engine running.
If I stop the engine (by magnetos OFF), then try to restart it by pressing the "S" key (after magnetos ON or not), the propeller cone spins, not the propeller, the engine turns and coughs, and the cowl  plugs are not ejected.

Also if I do a manual start with the cowl plugs.

It seems that they are ejected only if I use the Autostart.

**Comment by gilbertohasnofb** [comment]
@wlbragg I just pushed a commit removing the engine coughing due to plugs. 

And @dany is right about only the spinner moving when the engine is cranked. I think you want to eject the cowl plugs not when the engine is on but when `engines/active-engine/cranking` is `true`. This way, as soon as the propeller spins, the cowls will be ejected, regardless if the engine will manage to start or not (for instance, it might fail due to improper fuel mixture or no use of primer).

**Comment by gilbertohasnofb** [comment]
@wlbragg I just pushed some improvements to the fuel and baggage dialogs, they now show fuel in litres and baggage in kilograms as well.

Another thing I would like to ask you, could you please create a hotspot rectangle around the baggage door? I want the baggage door to be openeable only by the handle but I want it to be closed by clicking anywhere (in RL you would just hold it anywhere and bang it). But I don't want to make the interior part of the door a pick spot since it shows with the Ctrl+C and makes everything confusing. So ideally I would have a hotspot which will be hidden unless the baggage door is fully opened, the hotspot would be a simple rectangle which would completely encase the baggage door. Something like this (in green):

image

**Comment by wlbragg** [comment]
@gilbertohasnofb I noticed another bug. When you first start the sim and try to crank the propeller using the s key you get a prompt "Use the primer", but the propeller also doesn't crank. If you subsequently start using the autostart, then it will crank using the s key.
I haven't investigated that yet.

Back to the cowl plugs. I added "engines/active-engine/cranking" to the allowable/removable logic. 
But, that is not where it is changing the visibility of the cowl plugs if engine is running. In fact I can find no where that this happens. I don't see any logic that is tied to engine/running removing the cowl plugs?

**Comment by wlbragg** [comment]
@gilbertohasnofb I pushed a new BaggageDoorHotSpot and improved SumpHotSpotLeft/Right as well as the changes to the cowlplugs allowable/removable code.

Still haven't accounted for visibility or the other bug I have noticed, see post above.

**Comment by dany93** [comment]
@wlbragg 
Still, "engines/active-engine/cranking" seems the good criteria. We want the cowl plugs be removed as soon as the propeller is spinning. While "engines/active-engine/running" remains false as long as the engine is not truly running, even if the starter ("S") is activated.

**Comment by wlbragg** [comment]
>Still, "engines/active-engine/cranking" seems the good criteria.

Yes, that is right, I'm waiting because there should already be a code block removing the cowlplugs if the engine is running and I can't find it. So I have no idea as to why it is working at all as is. I want to add the "cranking" condition to the same code block, yet there is none. I never set up the removal code, @gilbertohasnofb  did it.

**Comment by gilbertohasnofb** [comment]
> I don't see any logic that is tied to engine/running removing the cowl plugs?

You possibly need to create a `<logic>` which is only enable when cranking is `true`, and that will have a `<value>false</value>` as input to the output `<property>/sim/model/c172p/securing/cowl-plugs-visible</property>`. This will work as a switch which will set that property to `false` whenever you crank the engine. Other than that you might want to look at `/Systems/ground-effects.xml` at lines 617 and 633, but that only controls whether the plugs are addable or removable given some conditions. And the objects themselves are defined at `Models/c172p.xml` from line 10822. If you want I can do the logic part myself.

> I noticed another bug. When you first start the sim and try to crank the propeller using the s key you get a prompt "Use the primer", but the propeller also doesn't crank. If you subsequently start using the autostart, then it will crank using the s key.
> I haven't investigated that yet.

Was this recently introduced? I don't remember this being an issue before. I can confirm the bug is on our `master` and is not affected by the securing aircraft options.

> I pushed a new BaggageDoorHotSpot and improved SumpHotSpotLeft/Right as well as the changes to the cowlplugs allowable/removable code.

The sumps need no extra code but I will do the baggage door a bit later, I am leaving for a couple of hours now.

**Comment by wlbragg** [comment]
@gilbertohasnofb I'm concerened because like you said the only logic in ground-effects.xml controls the addibility/removibility, nowhere is there logic that should be removing them now. How did you get it to remove them for "starting"? I didn't do that logic?

**Comment by wlbragg** [comment]
>Was this recently introduced?

I  don't think it was and I will investigate this one. Just haven't had the chance yet.

**Comment by wlbragg** [comment]
>How did you get it to remove them for "starting"? 

This is a rhetorical question. I know how I would/could do it, I simply am hesitant until I know where the existing code is that already removes them if engine/running.

**Comment by gilbertohasnofb** [comment]
@wlbragg hmm, I am about to push something... hope nothing get's lost, I absolutely hate rebasing 😭

**Comment by gilbertohasnofb** [comment]
@wlbragg everything seems fine here, my last two commits are showing normally on GitHub and `git pull` tells me I am up to date. My two last commits are:

https://github.com/c172p-team/c172p/pull/1181/commits/72f0090d9440aee10f513d39cfb7771d4d88e454
https://github.com/c172p-team/c172p/pull/1181/commits/931165d1c2a57da653d64e35da8ffa78c091f289

And I don't see your double commit, only a single one. Could you please make sure you see everything in your branch? `git log` shows all of mine and your commits on my side.

**Comment by gilbertohasnofb** [comment]
I am leaving now, but here is one more bug: you left the baggage door 'opened' in the model, I suspect you rotated it in order to have a reference for the hotspot but you forgot to put it back in the correct place. The code for the baggage hotspot is already working, just please fix the model.

**Comment by wlbragg** [comment]
@gilbertohasnofb  I had to merge again because of the blend file. I'm not sure what it is not liking about it. But I show every commit made in the commit section only some multiple times. It looks like a total mess. But i think it is all there.
@onox, if you get a chance you might look this over and tell me what I did wrong, if you can tell.
I thought I had this down but now it is being difficult again. Same thing I have been doing lately isn't working like it was. Or something changed?

**Comment by wlbragg** [comment]
@gilbertohasnofb  @onox my local looks correct, it is only here it looks messy.

**Comment by gilbertohasnofb** [comment]
Let's please stop pushing anything until we clear this up, it's too messy
right now. @onox can you give us a hand?

**Comment by gilbertohasnofb** [comment]
@wlbragg if you see the commit list [here](https://github.com/c172p-team/c172p/pull/1181/commits), there are three identical commits named 'Strap sits over propeller, propeller removes cowl plugs'. We definitely want to clear it up before proceeding, the remote is what matters not your local. We need to fix the remote and then you can even delete your local and then pull again.

**Comment by wlbragg** [comment]
@gilberto please see the new branch miscellaneous-issues. I cherry picked all the relative commits here and just created a new branch. I could have overwritten this branch but just in case I wanted to keep this one for comparison.
It the new branch looks correct to you we can make a new PR out of it and delete this one.

**Comment by gilbertohasnofb** [comment]
@wlbragg that branch looks good but I am a bit weary about this sort of solutions, I am just afraid some work/code might get lost. Are we sure everything is working over there? We must be a hundred percent sure before closing this one...

**Comment by wlbragg** [comment]
@gilbertohasnofb why don't I make a PR from it and we can both test it and look it over before we do anything with this PR. My reasoning for doing this is I am not sure what can be done to this one other than what I did and then overwriting it. But like you, I am afraid to overwrite it unless we are absolutely sure it is complete. It won't hurt to use the other PR and leave this one alone until we are positive, then we can simply delete this one.

**Comment by gilbertohasnofb** [comment]
All right, let's leave this open and let's move on to the other PR. Please check it as much as you can to make sure nothing is lost.

**Comment by gilbertohasnofb** [comment]
⚠️ ⚠️ ⚠️ ⚠️ ⚠️ ⚠️  DO NOT MERGE ⚠️ ⚠️ ⚠️ ⚠️ ⚠️ ⚠️

**Comment by gilbertohasnofb** [comment]
@wlbragg let's close this and delete this branch?

**Pull request closed without merging**
