### PR TITLE
Preflight to runup tutorials completed

### PR DESCRIPTION
**Pull request by legoboyvdlp**
@wlbragg if you would like to test and see if you get that issue that I mentioned?

### CODE REVIEW

**Comment by legoboyvdlp** [comment]
Apart from the pattern tutorial, all the tutorials are completed.

**Comment by wkitty42** [comment]
there is talk on the dev list of getting xDraconian's (aka scott) Hawaii custom scenery into terrasync... that's going to be another week or so from what i understand... that because of the changes being made to move terrasync into the AWS cloud...

**Comment by wlbragg** [comment]
>there is talk on the dev list of getting xDraconian's (aka scott) Hawaii custom scenery into terrasync.

Ah, yes, I forgot about that. Hopefully that gets in as well and then they can use use that as well in the included Hawaii scenery in the release.

I'm mostly concerned about not dropping this entire ball beings @legoboyvdlp took the time to redo these tutorials. Beings we're calling this next release a major release, this is an important part in IMHO.

So someone needs to post to the dev list that the tutorials are all finished and pointing at Hawaii to be included in the next release. Our work will be automatically included with our new version but unfortunately the Hawaii scenery chunk inclusion is not under our control.

**Comment by gilbertohasnofb** [comment]
@wkitty42 Thanks for the info concerning the scenery. If you see something more about it in the dev-list could you give us a shout here? Sometimes I miss some important info from that list due to the volume of emails I am currently receiving :cry: Thanks a lot!

**Comment by wlbragg** [comment]
@legoboyvdlp  if "Pattern" tutorial is supposed to start the aircraft, it isn't.

**Comment by legoboyvdlp** [comment]
Ok - didn't touch that at all, actually. It might have done years ago.

**Comment by legoboyvdlp** [comment]
The pattern tutorial started my aircraft here @wlbragg?

**Comment by wlbragg** [comment]
>The pattern tutorial started my aircraft here 

@legoboyvdlp it's the master and gen power switch, if they are set to off, it won't start until I switch them on.

**Comment by wlbragg** [comment]
@legoboyvdlp confirmed, I added

~~~
        <set>
            <property>/controls/switches/master-bat</property>
            <value>true</value>
        </set>
        <set>
            <property>/controls/switches/master-alt</property>
            <value>true</value>
        </set>
~~~
after line #102
~~~
<set>
            <property>/sim/model/c172p/brake-parking</property>
            <value>1</value>
        </set>
~~~
and it started successfully even if the switches were off.

**Comment by legoboyvdlp** [comment]
Ok, great!

**Comment by legoboyvdlp** [comment]
This can be merged imo?

**Comment by legoboyvdlp** [comment]
Bumping?

**Comment by wlbragg** [comment]
I just saw this, I'll take a look later tonight.

**Comment by wkitty42** [comment]
On 07/29/2018 10:14 PM, wlbragg wrote:
> Does anyone know if the Hawaii scenery in in fgdata now?

what's there now should be fine for testing... the other hasn't been added 
yet... hopefully it is still available if i'm reading the dev list correctly...

**Comment by gilbertohasnofb** [comment]
> So as far as I am concerned, this is good to merge

@wlbragg I think you forgot to click the green merge button :smile: 

> Does anyone know if the Hawaii scenery in in fgdata now?

Not as far as I know... could anyone please bring it up with them once again? I feel like I already sent them a million emails about it, both on and off the list... That scenery _must_ be included else it completely defeats the purpose of what we are doing. Shouldn't take so many months to add it after everyone seemed to agree with us...

@legoboyvdlp Thank you so much, lego!!!

**Comment by gilbertohasnofb** [comment]
@legoboyvdlp Next time please try to remember to add the phrase `Fixes #1097` (with the correct issue number, of course) for every issue that your PR fixes. This way they close automatically.

**Comment by legoboyvdlp** [comment]
Thanks! Happy to help. 

As for that, thanks, I'll try and remember for the next one.

**Comment by wkitty42** [comment]
On 08/06/2018 06:18 AM, Gilberto Agostinho wrote:
>     Does anyone know if the Hawaii scenery in in fgdata now?
> 
> Not as far as I know... could anyone please bring it up with them once again?
> I feel like I already sent them a million emails about it, both on and off
> the list... That scenery /must/ be included else it completely defeats the
> purpose of what we are doing. Shouldn't take so many months to add it after
> everyone seemed to agree with us...

until t[h]orsten (i can't remember which one it is) completes the move to AWS 
hosting, nothing much can be done with the scenery at all... that's my 
understanding... it is taking him longer to complete the scripting changes than 
was originally expected... something about real life and problems getting cut 
firewood for the upcoming winter...

**Comment by gilbertohasnofb** [comment]
But isn't it just a matter of copying the tiles into FGDATA? Couldn't anyone else with access simply copy them? They are like 50 Mb in total.

**Comment by gilbertohasnofb** [comment]
> i'll try to prod them again...

Really appreciate that, @wkitty42! Let us know if you get any answers. It should be really simple and I had already sent them the list of the correct tiles.

**Comment by wkitty42** [comment]
i'm copying this to the c172p team's issue tracker as well as the FG dev mailing 
list... i don't know if it will work but i'm gonna try it anyway ;)


On 07/19/2018 01:15 AM, Torsten Dreyer wrote:
> It is my understanding that this "time travel" feature is not related to the new 
> Hawaii scenery. The entire point about of getting more frequent scenery updates 
> is to have "up-to-date" scenery.
> Being able to conserve history is another story.
> 
> If nobody objects by Friday, I'll add your proposed changes to the upstream 
> terrasync over the weekend.


i know the above, written 2.5 weeks ago, is about getting scott's (xDraconian) 
Hawaii scenery into terrasync but we need to make sure it is also in FGData... 
we, the c172p team, are getting a little antsy about missing this scenery update 
as our tutorials are dependent on this new scenery being available...

can we, ahead of the scenery being placed into terrasync, get it into FGData so 
we know it is there and we can finish testing our craft and its tutorials before 
the branching is done?

we fully understand real life can get in the way sometimes... it happens to us, 
as well...


-- 
  NOTE: No off-list assistance is given without prior approval.
        *Please keep mailing list traffic on the list unless*
        *a signed and pre-paid contract is in effect with us.*

**Comment by wkitty42** [comment]
On 08/06/2018 12:28 PM, Gilberto Agostinho wrote:
>     i'll try to prod them again...
> 
> Really appreciate that, @wkitty42 <https://github.com/wkitty42>! Let us know if 
> you get any answers. It should be really simple and I had already sent them the 
> list of the correct tiles.


i just did and hopefully was successful at sending it to this issue as well as 
the mailing list... i tried to do it this way so you could see what i wrote... 
i'm hoping that it went into this issue OK...

**Comment by wkitty42** [comment]
>
>
> i know the above, written 2.5 weeks ago, is about getting scott's
> (xDraconian)
> Hawaii scenery into terrasync but we need to make sure it is also in
> FGData...
> we, the c172p team, are getting a little antsy about missing this scenery
> update
> as our tutorials are dependent on this new scenery being available...
>
>
May I ask to not add the scenery to FGData, please? If we want to ship it
with the base package and/or the binary installer, please just copy it over
during the build process. I already have support for adding the default
airports scenery and I would hate to (again) have machine maintained data
sitting within our git repo.

Torsten
-- 

Torsten Dreyer

**Comment by wkitty42** [comment]
Whatever gets done, please, could we make sure it is available to the user
- even one who doesn't use TerraSync, has a slow internet connection, etc
etc etc?
Many thanks,
Jonathan

**Comment by wlbragg** [comment]
>I am still a bit confused why Torsten does not want to add the scenery directly to FGData but only at the build time, what is the point of doing that

They don't want to add anymore data to fgdata. Instead I think the idea is to have it included with the release bundle but not residing in fgdata. Terrasync already has a version of Hawaii in it but it would be odd to have a better version only available from a new version install. So it really does still need to be included in terrasync.

**Comment by wkitty42** [comment]
> Whatever gets done, please, could we make sure it is available to the user
> - even one who doesn't use TerraSync, has a slow internet connection, etc
> etc etc?
>
>
Sure. As long as PHNL is our default airport this is already done, the
scenery gets included in the base package and the installers.
When we move to another default airport, all I have to do is to /add/ the
new tiles instead of replacing the tiles around PHNL. This is a simple
one-liner in the scripts.

And just for information why there is still no new Ohau Terrain availabe in
TerraSync: Changing the terrain mesh most likely needs resetting the
computed ground elevations in the scenemodels database. This will trigger a
fresh export of all Objects-stgs within the modified tiles. For all this, I
first need the scenemodels-db export fully established.

Just yesterday, I managed to complete a manually triggered dry-run of the
entire export batch running as a serverless AWS task. Dry-run means it
completes the export of  all /Models and /Objects directories (tens of
thousands of files), rebuilds the .dirindex files, creates a changelog
against the TerraSync master and performs a "rsync --dry-run" to simulate
the upload of the new or modified files to the TerraSync master.


-- 

Torsten Dreyer

**Comment by wkitty42** [comment]
On 08/06/2018 01:20 PM, wlbragg wrote:
>     something about real life and problems getting cut firewood for the upcoming
>     winter.
> 
> @wkitty42 <https://github.com/wkitty42> FYI:
> Thorsten is cutting wood and originally guided xDraconian's scenery build. 
> Torsten is working the scenery move to AWS hosting.


thanks! i told ya i get'em mixed up... i hate doing that, too...

**Comment by gilbertohasnofb** [comment]
> Sure. As long as PHNL is our default airport this is already done, the scenery gets included in the base package and the installers. When we move to another default airport, all I have to do is to /add/ the new tiles instead of replacing the tiles around PHNL. This is a simple one-liner in the scripts.

Is PHNL going to continue to be the default airport in the next release? I haven't been following that. Also, are all the tiles containing both islands of Hawaii included?

**Comment by wlbragg** [comment]
@wkitty42 Thank you for dealing with this, it is very time consuming for me to try to keep this issue moving in the developer discussion, I really appreciate you taking the lead with this communication.
FYI: the concept was Hawaii (the entire chain) was to "always" be included with every release regardless of the "default airport" for that release. The reason being we get too many bug reports for new installs not having the scenery the tutorials use and we don't have the manpower to rewrite tutorial every release.
We don't care how it gets done, whether or not it is the default airport. I think they need to make sure it is "permanently" accounted for regardless of which airport is the default. Otherwise they are simply kicking the can down the road and we will be back here next release. It would be nice to put this to bed.

**Comment by gilbertohasnofb** [comment]
> We don't care how it gets done, whether or not it is the default airport. I think they need to make sure it is "permanently" accounted for regardless of which airport is the default. 

:+1: 

But if I understand what Torsten wrote, he is saying that right now we don't need to do anything since PHNL is the default airport. Once it is not they will need to add a one liner to the script in order to accommodate this. So as long as this line is added in the future we should be good to go.

**Comment by wkitty42** [comment]
On 08/06/2018 03:51 PM, Gilberto Agostinho wrote:
> Is PHNL going to continue to be the default airport in the next release? I 
> haven't been following that.

yes... i think they're going to one main release a year that will carry a new 
default airport and then there will be three maintenance releases... so still 
four releases a year but only one default airport change each year...


> Also, are all the tiles containing both islands of Hawaii included?


AFAIK, the tiles we requested are the ones being included... don't they cover 
the whole island chain?

**Comment by wkitty42** [comment]
On 08/06/2018 04:03 PM, wlbragg wrote:
> @wkitty42 <https://github.com/wkitty42> Thank you for dealing with this, it
> is very time consuming for me to try to keep this issue moving in the
> developer discussion, I really appreciate you taking the lead with this
> communication.

i was available to ring the bell this time ;)


> FYI: the concept was Hawaii (the entire chain) was to "always" be included
> with every release regardless of the "default airport" for that release. The
> reason being we get too many bug reports for new installs not having the
> scenery the tutorials use and we don't have the manpower to rewrite tutorial
> every release.

i forgot about that... looks like it will either have to be included by the 
release build scripts along with whatever other default airport there is OR 
it'll end up in FGData anyway... i guess they'll just keep adding it to the 
release archive build...


> We don't care how it gets done, whether or not it is the default airport. I 
> think they need to make sure it is "permanently" accounted for regardless of 
> which airport is the default. Otherwise they are simply kicking the can down 
> the road and we will be back here next release. It would be nice to put this 
> to bed.

agreed... the frustrating part is the waiting...

**Pull request merged**
