### PR TITLE
darker vent textures

### LINKED ISSUE #1184: Vents are too light
image

image

Seems this got broken along the way?

### PR DESCRIPTION
**Pull request by gilbertohasnofb**
Fixes #1184

Improves vent textures matching their colours to the surroundings.

### CODE REVIEW

**Comment by gilbertohasnofb** [comment]
@wlbragg vent textures now match the cockpit colour. The only issue is that the OAT is substantially lighter than the other vent for some reason beyond my knowledge, I suspect this needs to be fixed in the 3D modelling side. See:

image

image

To be clear, the tube itself in the second picture is fine, the issue is in the OAT only:

image

**Comment by wlbragg** [comment]
@gilbertohasnofb I guess we want to change the texture for the oat then to wha tthe rest of the vent is now using?
oat

**Comment by gilbertohasnofb** [comment]
@wlbragg I didn't know the face was mapped to that place. That's easy enough for me to fix, I will get it done now.

**Comment by gilbertohasnofb** [comment]
@wlbragg done, ready to be merged.

**Comment by wlbragg** [comment]
@gilbertohasnofb I think you missed my comment...
>Beware, the needle uses that white section. I suggest you add the new color to the upper left area.

Which was also wrong as I meant to say...
Beware, the needle uses that white section. I suggest you add the new color to the upper RIGHT area.

**Comment by gilbertohasnofb** [comment]
@wlbragg My bad, I fixed it now. The new (darker) background texture is now on the top right and needs to be UV-mapped. Please feel free to merge this yourself once this is done.

**Pull request merged**
