### PR TITLE
Miscellaneous fixes/corrections

### LINKED ISSUE #1401: Force invert-mouse-wheel = true
FG gives us a choice if we want the mouse wheel to work in reverse (menu "File" -> "Mouse Configuration" -> "Reverse mouse wheel direction" which sets the `/sim/mouse/invert-mouse-wheel` property). So why in Cessna we are forced to use reverse mouse wheel? I mean instruction in the c172p-main.xml file:

```
<!-- Fix scrolling direction of knobs -->.
<mouse>
    <invert-mouse-wheel type="bool">true</invert-mouse-wheel>.
</mouse>
```

This instruction causes my autosave file to be overwritten and I have to uncheck "Reverse mouse wheel direction" every time (I prefere without reverse). I also didn't noticed any problem with knobs after removing this instruction at all.

### LINKED ISSUE #1404: Miscellaneous fixes/corrections
This issue is to make record of a couple miscellaneous fixes and corrections.

1. A couple .ac model errors such as the Avionics switch and some breakers located in the wrong .ac file.
2. KAP and GFC autopilot variables removed from main set because they are now contained in the individual variant set files.

### PR DESCRIPTION
**Pull request by wlbragg**
Fixes #1404 
Fixes #1401

### CODE REVIEW

**Comment by wlbragg** [comment]
@legoboyvdlp or @dany93 

Could either of you in your spare time check this and merge please. A couple minor outstanding issues upstream I had fixed on my local machine that need to get merged. The autopilot stuff is just duplicate code but the .ac work correct some visual bugs.

I plan on getting back into this a bit and try to clear some of the "already recorded" issues over the next months.

Thanks.

**Comment by dany93** [comment]
Hi @wlbragg 

I'm not sure what to check.
The aircraft starts, no problem. No visual bugs at first view.

AP KAP 140:
- Maybe I don't remember something, but clicking on the 'Autopilot Arm/Disarm' left button (in the cockpit 3D instrument) makes nothing. I believed it was a 'Start' button (?). Some Click animation seems not working.
- I have to open the "Autopilot settings" interface in the Menu to have it working. And even like this, it is erratic, I have to click several times or / and on other buttons. I don't understand. After this, the 3D buttons in the instrument work.
- In ALT mode, the AP stabilizes 200 ft above the ALT setting.


A few alert messages, which don't seem to be a real issue. Maybe not new ones.
```
  10.90 [ALRT]:autopilot  DigitalFilter: unknown config node: absolute
  11.82 [ALRT]:autopilot  DigitalFilter: unknown config node: value


  202.98 [ALRT]:nasal      ERROR: Cannot add listener to tied property /controls[0]/lighting[0]/strobe[0]
  208.22 [ALRT]:nasal      ERROR: Cannot add listener to tied property /controls[0]/gear[0]/brake-parking[0]
  210.44 [ALRT]:nasal      ERROR: Cannot add listener to tied property /controls[0]/gear[0]/brake-parking[0]
  215.98 [ALRT]:nasal      ERROR: Cannot add listener to tied property /controls[0]/anti-ice[0]/pitot-heat[0]
  217.17 [ALRT]:nasal      ERROR: Cannot add listener to tied property /controls[0]/lighting[0]/nav-lights[0]
  217.99 [ALRT]:nasal      ERROR: Cannot add listener to tied property /controls[0]/anti-ice[0]/pitot-heat[0]
  218.45 [ALRT]:nasal      ERROR: Cannot add listener to tied property /controls[0]/anti-ice[0]/pitot-heat[0]
  218.84 [ALRT]:nasal      ERROR: Cannot add listener to tied property /controls[0]/anti-ice[0]/pitot-heat[0]
  256.27 [ALRT]:nasal      ERROR: Cannot add listener to tied property /controls[0]/gear[0]/brake-parking[0]
  263.36 [ALRT]:nasal      ERROR: Cannot add listener to tied property /controls[0]/anti-ice[0]/pitot-heat[0]
  263.70 [ALRT]:nasal      ERROR: Cannot add listener to tied property /controls[0]/anti-ice[0]/pitot-heat[0]
  264.06 [ALRT]:nasal      ERROR: Cannot add listener to tied property /controls[0]/lighting[0]/nav-lights[0]

 177.07 [ALRT]:cockpit    empty 'not' condition (several times)


```

**Comment by wkitty42** [comment]
On 8/4/22 6:35 AM, dany93 wrote:
> AP KAP 140:
> 
>   * Maybe I don't remember something, but clicking on the 'Autopilot Arm/Disarm'
>     left button (in the cockpit 3D instrument) makes nothing. I believed it was
>     a 'Start' button (?). Some Click animation seems not working.

IIRC, you have to hold, not click, the button... hold it for a couple of seconds...

**Comment by dany93** [comment]
Thank you @wkitty42

Weird idea. But...

Same no effect by holding it, even several seconds.
A workaround seems, **in the dialog box** (Menu, Autopilot settings) to try every button. At least, the "Baro" button did something. At least once for me.

I checked. In a previous version (0112f9fb), the AP button on the 3D instrument activated the AP.

**Comment by wlbragg** [comment]
@dany93 sorry, this was kind of out of the blue. But all I did was remove a chunk of duplicated autopilot init code in the "main" or "common" set file. I removed it because it is now contained in all the individual variant set files, custom to that variant set file. For example, the c172sp variants have either a GFC or KAP autopilot respectively, all the other variants have the KAP. So either the KAP and GFC init code, depending on the variant, is in their individual set.xml file. I tested it and everything worked fine. If your having autopilot issues, maybe you need to clear the c172p airplane data cache before you try the latest master branch.
One way to verify would be to switch your local c172p copy to the most current git dev master branch and see if the autopilot is working. If so then switching to this PR branch should also still work.
The only other change was a misplaced "Avionics" switch in a .ac file. You can verify that in the latest development master branch, by toggling the Avionics switch and you can see the duplicate doesn't toggle and remains in place.
@wkitty42 did you try this PR branch?

**Comment by wlbragg** [comment]
@dany93 
The only errors that concern me are...

10.90 [ALRT]:autopilot  DigitalFilter: unknown config node: absolute
 11.82 [ALRT]:autopilot  DigitalFilter: unknown config node: value
Those look new to me, I'll have to research. I have a feeling they are from some added debug reporting from core dev maybe.

The "tied property" warnings you can ignore

This next one is new to me also

 177.07 [ALRT]:cockpit    empty 'not' condition (several times)

But I think this is also from some relatively new and more robust dev debug logging and reporting work. But we need to eventually track those down and fix them. They are most likely in the JSBSim logic code.

**Comment by wlbragg** [comment]
@dany93 I just checked and none of those errors are related. I have them as well and my AP is working. Plus they are also generated from the current fgdata c172p. It's all just new more robust error and warning reporting from core work. Stuff we should try to track down and correct eventually, nut nothing to do with any of this.

**Comment by wkitty42** [comment]
On 8/4/22 4:17 PM, wlbragg wrote:
> @wkitty42 <https://github.com/wkitty42> did you try this PR branch?

i have not (yet)... gotta figure out how without mucking up my local... i 
generally just pull and test main branch because easier... i'm still a very 
green git noob and use a script based on some parts of dnc to pull and update my 
dev c172p...

**Comment by dany93** [comment]
I think I have succeeded. Description will follow.

**Comment by dany93** [comment]
Thanks @wkitty42 for your clue on holding "AP". I had to hold it a fraction of a second to have the AP start.
Is it on purpose ? Weird idea, I've never seen this. I see this rather as kind of a trap.

C1272P default, 160 hp.
KAP 140.

Another clue : to start the AP, one have to validate the Atm Pressure setting first.

Now, the KAP 140 works by clicking the buttons in the cockpit.

@wlbragg, do you think there are other items to check ? If this is sufficient, I will merge it.

**Comment by wkitty42** [comment]
On 8/5/22 11:39 AM, dany93 wrote:
> Thanks @wkitty42 <https://github.com/wkitty42> for your clue on holding "AP". I 
> had to hold it a fraction of a second to have the AP start.
> Is it on purpose ? Weird idea, I've never seen this. I see this rather as kind 
> of a trap.

AIUI, yes... you have to hold the real one, too... at least, that's what i've 
been told... i guess to avoid accidental engagement or disengagement...

**Comment by dany93** [comment]
@wkitty42 wrote
> you have to hold the real one, too... at least, that's what i've
been told... 

True. It's written in the KAP140 Guide (0.25 sec).
>For software version 03/01 and later, the AP button must be pressed and held for 0.25 seconds to engage the autopilot.

@wlbragg 
This Issue https://github.com/c172p-team/c172p/issues/1401 has never been fixed.
I think that we should delete or comment these lines:
c172p-main.xml, l. 549-551
```
        <mouse>
            <invert-mouse-wheel type="bool">true</invert-mouse-wheel>
        </mouse>
```
Otherwise, throttle, mixture, elevator trim controls by mouse scroll wheel are inverted.
Knobs are an endless discussion (I prefer not inverted for these too).
Could you do it please ?

**Comment by wlbragg** [comment]
Refreshing my memory now at to "invert".

@dany93 , as far as testing the current work, we are good to go. but please wait to merge. I have one other thing I want to add to this PR, a minor float spray/wake particle effect change. The float particles originally were a rushed job by me a long time ago and has always bothered me. They are over the top and sloppy in execution. I want to clean them up a bit. Also I will revisit the https://github.com/c172p-team/c172p/issues/1401 and and comment on it. Thanks everyone, stay tuned.

**Comment by wlbragg** [comment]
@dany93 
@wkitty42 
@PlayeRom 

Current mouse wheel behavior...

forward/away scrolls knobs left
backwards/towards scrolls knobs right

forward/away pulls throttle/mixture sliders towards
backwards/towards pushes throttle/mixture sliders away

forward/away pulls air vents sliders towards
backwards/towards pushes air vents sliders away

forward/away pulls sun visor sliders towards
backwards/towards pushes sun visor sliders away

forward/away pulls overhead light controls sliders towards
backwards/towards pushes overhead light controls sliders away

Of all these motions, ONLY the overhead light controls feel correct to me.

@dany93 as far as your request to check MSFS per #1330 , as to which I never did, I just checked it and it is opposite what we do and I think it feels more correct or intuitive.

So I agree with those that think we need to remove
<invert-mouse-wheel type="bool">true</invert-mouse-wheel>

If all are in agreement, I will push that change to this PR as well?
I will add Fixes https://github.com/c172p-team/c172p/issues/1401 to this PR.
I also will see if I can reverse the overhead light switches so the continue to feel correct.

**Comment by dany93** [comment]
> @dany93 as far as your request to check MSFS per https://github.com/c172p-team/c172p/issues/1330 , as to which I never did,.....

In a previous version if I remember well, `git blame` gave @onox as the author of this change. I don't understand why (only for the knobs, as written ?).
> If all are in agreement, I will push that change to this PR as well?

Yes, please.
It will also fix the flaps lever, currently counter intuitive too.

If I understand well, you are not finished? Waiting for your signal before merging.

**Comment by wlbragg** [comment]
@dany93 
I'm finished. I think the flaps lever will feel correct to you now because of this invert change.

The only thing I am curious about is what you think of the dials direction now. So, all the knobs feel correct, but the dials in the instruments, feel backwards. Such as the nav's, heading, heading offset. What do you think? Their knobs turn correctly, but the dials are now reversed. Do you think we need to invert the dials in each of their respective xml's. It will be a bit of work, but might be necessary.

I also pushed the change I wanted to make to the float particle effects. It's not exactly what I want, but better and less heavy than it was. One of these days I am going to make a particle editor so we can get perfect particles.

**Comment by dany93** [comment]
@wlbragg 
Thanks for the invert-mouse-wheel.

Everything seems correct to me.
- Throttle, mixture, flaps lever: correct.
- Knobs and dials:
Mouse scroll wheel pushed away: dials (**values**) increase. Unequivocal for the values (radio frequencies, altimeter setting, KAP 140 altitude setting, etc...).
Also, knobs rotate clockwise. This rotating preference vs mouse scroll-wheel is subjective and matter of discussions. Now, for me, I feel it correct (maybe I'm used to it). Anyway, knobs rotating clockwise always give values increasing on any instruments or amplifiers.
> the dials in the instruments, feel backwards. Such as the nav's/vor's, heading, heading offset. What do you think? Their knobs turn correctly to the mouse scroll, but the dials are reversed to the knob direction.

Right, the dials (I think you mean the **rotating scale**s in Heading offset, VORs, ADF) turn counter-clockwise, contrary to the knobs. But if you consider the **values** (degrees) they increase. Which is consistent.
I see no problem for the heading bug.

The float particle effect is already not as bad as you write IMO.

**Comment by PlayeRom** [comment]
Thank you for considering my reported issue about remove `invert-mouse-wheel`.

**Comment by onox** [comment]
Does removing the `<invert-mouse-wheel>` hack change the behavior compared to https://github.com/c172p-team/c172p/issues/1330#issuecomment-682471996 ? At the time the hack was needed to make sure mouse behavior corresponded with the animations of objects in the cockpit, not with the values in the tooltips. Some users agreed, others disagreed. Making it consistent with the behavior of other flight sims is a good argument to remove it though.

IIRC the bigger problem is that (at least several years ago) FG does not know that certain objects in a 3D model are a dial/lever/button/yoke. Everything is just an anonymous object that can be translated/rotated/scaled. If FG knew the type and behavior of certain objects, then it could provide options in FG's launcher that allow the user to specify how certain Human Interface Devices (mouse/keyboard/gamepad/joystick) must interact with certain objects. For example, if a cockpit has a lever that must be moved downward to increase the flaps, a mouse user might wish to scroll 'down' to increase its value (so that the behavior of the mouse corresponds with the physical behavior of the lever), but for a user with gamepad they may simply want dpad UP or R1 to correspond with increasing the flaps.

If FG had support for 'actions' (like moving flap lever down or retracting gear) the user would be able to specify the mapping between input and actions in FG's launcher. Then the movement of the camera and/or yoke could be inverted if desired by the user. (See the input settings screen of any AAA PC game to see what I mean) Requiring users to mess with xml files to configure a gamepad/joystick for a certain airplane model would then also be a thing of the past.

**Comment by wlbragg** [comment]
@onox thanks for the info. Nice to see you around.

@dany93 thanks for your time and efforts. You mention the overhead. As far as I'm concerned they're correct. Scroll forward they move right scroll backwards they move left, from a position of looking straight up while you're underneath of them. It seems correct to me. The comment you made about the dials moving in the correct direction as far as numerical change, you're right, in that respect it seems correct and it does match at least one other SIM we checked.

@PlayeRom your welcome and thank you for reporting.

**Comment by dany93** [comment]
@onox 
Glad to read you again.

@onox wrote
> Does removing the <invert-mouse-wheel> hack change the behavior compared to https://github.com/c172p-team/c172p/issues/1330#issuecomment-682471996 ?

I don't know because the video link in https://github.com/c172p-team/c172p/issues/1330#issuecomment-682471996 has been deleted.
All that I know is that it is a long and tortuous story. In [#63467c6 ](https://github.com/c172p-team/c172p/commit/63467c62e6122e59143675076a6c840be8fea11d) and [this commit](https://github.com/c172p-team/c172p/commit/996d98dc2a1a72e18a1cdf23c09beb37d11dbaca#diff-27a8827c68ad6ec82a337698c81c1790adcea6c3c63ab5dbfb17accf462e24c1),  @gilbertohasnofb changed it from `true` to `false`. Like this, it became  true, then false etc... 3 or 4 times ((I let you for even or odd).
In the previous versions (before this issue, and from [this version](https://github.com/c172p-team/c172p/blob/57050e42025e07f1fc47c1e62e2ebae05ca65ee7/c172p-main.xml)) it was true and everything was inverted (value increments, animations).

We can hope that, now, everything is correct (see the messages above). Or, at least, at best for most people.

**Comment by onox** [comment]
Hi everyone :slightly_smiling_face: 

I remember it was indeed an issue that goes back many years.

How does the c172p look like nowadays? Does it still have the mechanical instruments or does it have some glass cockpit? Can you still choose between the bush/ski/amph variants or does everything go through FG's launcher?

**Comment by wlbragg** [comment]
We have a FG1000 variant c172sp "glass cockpit". The interiors pretty close to the real thing but the exterior really needs to have a new model. I did the electrical for it, but it still needs some mechanical such as the fuel injection. It's only selectable through the UI. But all the change outs, engine,  ski, float, etc. still available on the fly or UI. We added a few more UI selectable options like multiple fuel tank variations, rudder trim. I just saw a report of a c-172 tail drag option, I'm mulling over maybe adding it. It seems like it's kind of going backwards but if they had one I feel we should too. Development hasn't been too active over the last year or so. Flurries of activity here and there, I plan on getting back on a little bit more.

**Pull request merged**
