### PR TITLE
Fuel selector objects pointing at wrong effect file

### LINKED ISSUE #1394: Fuel selector pointing to wrong effect file in default variant

### PR DESCRIPTION
**Pull request by wlbragg**
Fixes #1394 

@legoboyvdlp if you don't mind, when you get a chance please review, merge and close. It's minor but I can't believe we never noticed.

### CODE REVIEW

**Comment by legoboyvdlp** [comment]
Wait, if you re-added lm-interior-fuel-selector.eff but changed the object to inherit from <inherits-from>Aircraft/c172p/Models/Effects/interior/lm-fuel</inherits-from>, how does that work? Am I missing something?

**Comment by wlbragg** [comment]
Yeah, I first pointed it to what I thought was supposed to be the correct effect file. Then I realized the issue wasn't that it was  pointing to the wrong effect file at all. It was that the effect file it was pointing to was missing. So in the second commit I reversed the first commit and added the missing effect file.
Let me know if that doesn't make sense to you.
So, first commit was wrong, second commit reversed the first commit and added the missing effect file.

**Comment by legoboyvdlp** [comment]
OK - thanks - I'll try and review this tomorrow morning

**Comment by wlbragg** [comment]
Thank you @legoboyvdlp

**Pull request merged**
