### PR TITLE
Add support for clustered shader lighting and Compositor ready

### LINKED ISSUE #1349: Compositor Conversion Plus Clustered-Shading Lighting
As the title says.

Use Compositor enabled FlightGear
Disable ALS
Enable Model shader.
When Lights blink, they cast shadows.

fgfs-20210104181720
fgfs-20210104181725

### PR DESCRIPTION
**Pull request by legoboyvdlp**
Fixes #1349

For my part this is ready to go. Any and all testing appreciated and I think we still need to decide on backwards compatibility. I'm in favour of tagging one last 2020.3 release and then merging this, with possible cherry picks for backporting as required.

image

### CODE REVIEW

**Comment by wlbragg** [comment]
@legoboyvdlp 
Have you tagged a release? There are instructions here somewhere, I never actually did this but I am sure I could figure it out.
If I cherry pick a few items here, I have identified at least three I think, back to master, would you have a problem attempting to tag the 2020.3 release. I will test this PR in the meantime and then I will merge this. I will pick the needed commits hopefully by late tonight. I will let you know when I am done.

**Comment by wlbragg** [comment]
@legoboyvdlp 
There wasn't but one small addition that needed to go into master. I forgot the iCCP Color Profile already has, which was another I was thinking if. I couldn't cherry pick the other change "init var in electrical.nas" as it was commingled with stuff that can't go to the master for 2020.3 release. So I pushed that directly to master. I think it was important enough to make sure it got in to that release.
So unless you can think of something else that needs to go to the 2020.3 release, I think it is as ready as it is going to be to tag.

**Comment by legoboyvdlp** [comment]
> Have you tagged a release? There are instructions here somewhere, I never actually did this but I am sure I could figure it out.
If I cherry pick a few items here, I have identified at least three I think, back to master, would you have a problem attempting to tag the 2020.3 release. I will test this PR in the meantime and then I will merge this. I will pick the needed commits hopefully by late tonight. I will let you know when I am done.

Sure thing! Once you let me know I'll make the tag

**Comment by legoboyvdlp** [comment]
Done, and list notified.

**Master is now 2020.4 or later, with minimum-fg-version tag**

**Comment by wlbragg** [comment]
@legoboyvdlp 
Wow, thank you for taking care of that. I want to test this a bit more and then I'll merge and start working on the kap140 integration. I want to take that one commit at a time and make sure I get it implemented correctly.
I'll be out of touch till later tonight.

**Comment by legoboyvdlp** [comment]
It's relatively straightforward, Onox left us good instructions!

You're welcome; thanks for looking after the merging!

**Comment by legoboyvdlp** [comment]
Is this good to go?

**Comment by wlbragg** [comment]
@legoboyvdlp 

Sorry, I've been totally away for the last couple weeks. This is not quite ready, I found something with the interior residual lighting that needs to be fixed. I plan on starting back up on it this next week.

**Comment by wlbragg** [comment]
@legoboyvdlp I am going to finish this by the end of next 2 weeks so we can get it merged. Then I want to merge the fg1000 addition which at a point I think we should merge it. But I want to do it in order with the compositor changes first. After that I want to finish the kap140 upgrade from the 182. Just giving you a heads up. 
Time for me to get back to work. I just got a new laptop that is helping me with some time constraints. Plus it is really a powerhouse and making computing "fun" again.
32.0 GB Intel(R) Core(TM) i7-9750H CPU
2 x 1 TB SSD's
NVidia RTX2070 Max-Q
So nice to have NVidia again with FG.

**Review by wlbragg — APPROVED** [review]
@legoboyvdlp this is ready to go as far as I am concerned.

I would request you check out the interior lighting scheme under ALS with and without the model shader enabled and under the Low spec option with and without the "Use shader" option checked.

As far as I remember, that are of the rendering was the last part that needed reviewed.

All I did since you looked at this last was to basically revert the use of checking the model shader for low spec vs als back to using skydome as it is still the predominate flag between the two. Also, since the ALS rendering side now has the model shader flag either on or off, if the model shader is turned off under ALS we change the interior lighting back to low spec material animations instead of ALS shader effects and lightmaps.

Once this is merged I will fix the couple of conflicts in the fg1000 branch/pr and prepare it for your review and eventual merge as well.

**Comment by wlbragg** [comment]
One more thing. i noticed, 2020.3.9 which is what I downloaded for Windows from the FG website, billed as the most current FG available (other than building next yourself or a nightly), didn't have the new more modern layout that is in next. But the changes I made still seem to fit it well with the exception of the model shader set at 1 (which is no longer capable in next). My question is can we ignore 2020.3.9 and make our next version compatible with 2020.4+?
It works fine with 2020.3.9, but if you set the model shader to 1 you get no interior lighting effects. I can fix that easy enough. It is a matter of changing a flag from model shader = 0 to model shader < 2 in about 44 different files. We should decide before merging this.

**Comment by legoboyvdlp** [comment]
Alright. I'll check it out and make sure nothing looks obviously wrong!

**Comment by legoboyvdlp** [comment]
Hey @wlbragg 

Everything looks fine with the clustered lights. However, I think there's a problem with the instrument lights. The radio light knob works; but this is what I get with the instrument lights, and no post or flood lights. 

image

**Comment by legoboyvdlp** [comment]
OK - I've checked out 2020.3.9.

`My question is can we ignore 2020.3.9 and make our next version compatible with 2020.4+?`

Given that there's a large warning that it only supports 2020.4, I don't see any need. We can keep updating the release/2020.3 branch by cherry picking if we need to? 

However, I don't fully understand all this. If its a simple change that adds compatibility for 2020.3.9 that doesn't negatively impact 2020.4 then go ahead.



I can confirm that things look as normal on 2020.3.9 --> EXCEPT that there are no exterior lights at all.

**Comment by legoboyvdlp** [comment]
ALS on, model shader enabled:
image


ALS on, model shader disabled:
image





It's actually problematic because if you have autosaved model shader settings from 2020.3.9:
image

That's by default, before turning the model shader off and then back on.






The only problem I've identified is when you start FlightGear when you have autosaved shader settings from 2020.3.9. Otherwise everything looks normal.

**Comment by wlbragg** [comment]
I guess I was once again confused by the versioning scheme.
Long term stable is what our last release supports. Is 2020.3.9 now considered our LTS?
It really doesn't matter. Our las release is 2020.3 and that work correctly all the way up to 2020.3.9.
So our next c172p release will be 2020.4 and that is this current version in master and the other issues we are working now. So no, I don't want to add and unnecessary code to support any 2020.3.x version.
Thanks for helping me to clarify that in my own mind.

OK, we are then good to merge this now.

This opens the door for the next set of improvements including fg1000 and kap140 upgrade. We can hopefully get those merged within a few days to a week for the fg1000 and a little longer for kap140.

Thanks

**Comment by wkitty42** [comment]
> I guess I was once again confused by the versioning scheme.
> Long term stable is what our last release supports. Is 2020.3.9 now considered our LTS?

2020.3.* are LTS but only the latest one is supported for the next 2(?) years after its release...

> It really doesn't matter. Our last release is 2020.3 and that work correctly all the way up to 2020.3.9.

that's how it should be... we should also have intermediate releases for it to fix any bugs that may appear as the LTS fixes bugs in it...

> So our next c172p release will be 2020.4 and that is this current version in master and the other issues we are working now. So no, I don't want to add and unnecessary code to support any 2020.3.x version.

that's understandable to a point... fixes in the craft's 2020.4 can be cherry picked back to the 2020.3 LTS branch if/when needed... and same for fixes to 2020.3 if we find something in there that has to be fixed and can be picked forward to the 2020.4 branch or master or whatever it is called...

**Comment by wlbragg** [comment]
Thank you!

**Pull request merged**
