### PR TITLE
New rating

### PR DESCRIPTION
**Pull request by gilbertohasnofb**
setting model and FDM ratings to 5 stars

### CODE REVIEW

**Comment by gilbertohasnofb** [comment]
@onox @wlbragg @legoboyvdlp @dany93 as discussed, this PR modifies the rating of our aircraft.

**Comment by gilbertohasnofb** [comment]
By the way, I also updated the ratings in our wiki page: http://wiki.flightgear.org/Cessna_172P

**Comment by legoboyvdlp** [comment]
Looks fine to me :+1:

**Comment by wlbragg** [comment]
I'll wait a bit longer for ANY feedback and then merge!

**Comment by gilbertohasnofb** [comment]
@wlbragg it is up to you, but I think @dany93 already gave his opinion in the team discussion, we just haven't heard from @onox

**Comment by gilbertohasnofb** [comment]
@wlbragg about your message, if there is still time this could be cherry-picked into the release and merged into FGData (or has FG 2018.3 been released already?). But this is quite minor, to be honest, and it's also fine if this makes its way to FGData only for the next release.

**Comment by wlbragg** [comment]
@gilbertohasnofb I'll just let it go. I'm sure if it was a major bug there is still time, but I hate to ask for it unless we have a bad bug to go with it. :smile:

**Comment by gilbertohasnofb** [comment]
100% agreed!

**Pull request merged**
