### PR TITLE
Fix issue of cowl plug being stuck in some tutorial

### LINKED ISSUE #1263: Taxing tutorial has bug around cowl plug removal
See: https://forum.flightgear.org/viewtopic.php?f=25&t=35473

What I discovered so far is that if the cowl plug is in place, on every other tutorial start it won't be removed and the tutorial fails.
It appeared to not matter whether or not the rest of the items were checked or not, and it was only every other time you tried to run the tutorial with the cowl plugs in place.

### PR DESCRIPTION
**Pull request by gilbertohasnofb**
Fixes #1263

### CODE REVIEW

**Comment by gilbertohasnofb** [comment]
@wlbragg I believe this PR solves that issue, could you please test it?

**Comment by wlbragg** [comment]
Wow, I am having a really bad issue. I keep getting a segmentation fault and the one common denominator is
~~~
   77.60 [ALRT]:nasal      Nasal runtime error: Timer is running, cannot change type between real/sim time
   77.60 [ALRT]:nasal        at /mnt/GDrive/Aircraft/Development Aircraft/c172p/Nasal/engine.nas, line 500
   77.60 [ALRT]:nasal        called from: /home/wayne/FGFS/install/flightgear/fgdata/Nasal/globals.nas, line 119
~~~
I need to remove that timer from happening and see if the tutorial still segfaults.

**Comment by wlbragg** [comment]
here is the scenario.
First I clear aircraft cache to have a clean start.
Startup sim and un-check "Complex aircraft engine procedures and failures" (I thought this would only matter if it was checked but it also fails if unchecked).
Start taxing tutorial with all the securing items checked.
After the aircraft starts and your ready to go to the next step, change view to outside and scroll around the aircraft.
Go back to interior view and stop the tutorial.
Shut engine down and recheck all the securing items.
Start tutorial again, "Complex aircraft engine procedures and failures" is still un-checked.
This is when I get a segfault.
If I restart the sim again and try to run the taxing tutorial I get an immediate segfault.

Also something at one point set the aircraft cache to 
~~~
<engines>
    <active-engine>
      <carb_icing_allowed type="bool">true</carb_icing_allowed>
      <oil_consumption_allowed type="bool">true</oil_consumption_allowed>
      <oil-service-hours type="double">0</oil-service-hours>
      <oil-level type="double">7</oil-level>
      <complex-engine-procedures type="bool">true</complex-engine-procedures>
    </active-engine>
    <engine>
    </engine>
  </engines>
~~~
Even thought in the sim GUI "Complex aircraft engine procedures and failures" is still un-checked.
And I am now getting "fault" at various locations but there is always that nasal error somewhere in log.

**Comment by wlbragg** [comment]
Now even after clearing the cache I get this as soon as the tutorial starts the aircraft.
~~~
   77.02 [ALRT]:nasal      Nasal runtime error: Timer is running, cannot change type between real/sim time
   77.02 [ALRT]:nasal        at /mnt/GDrive/Aircraft/Development Aircraft/c172p/Nasal/engine.nas, line 500
   77.02 [ALRT]:nasal        called from: /home/wayne/FGFS/install/flightgear/fgdata/Nasal/globals.nas, line 119
   77.02 [ALRT]:nasal      Electrical system initialized
   77.02 [ALRT]:nasal      Astro Tech LC-2 Chronometer Loaded
   82.02 [ALRT]:nasal      Starter on
   83.89 [ALRT]:nasal      Nasal runtime error: too few function args (have 0 need 14)
   83.89 [ALRT]:nasal        at 
Segmentation fault
~~~

**Comment by wlbragg** [comment]
I think all you really need to do to see the issue is start and stop the tutorial, shut the engine off and start the tutorial again.
I can't figure out how to isolate the timer or stop it without causing other segfaults or nasal errors for other reasons.

**Comment by wlbragg** [comment]
Where is this variable ever used?
oil_consumption.simulatedTime = 1;

**Comment by wlbragg** [comment]
I can't test this as before because I can't start and stop the tutorial twice as I did before to see if the changes you made worked for the original issue.

**Comment by legoboyvdlp** [comment]
> Bool telling whether the timer is using simulated time (which accounts for pause, etc.). Defaults to false (use real time). Can be both read and set. This cannot be changed while the timer is running.

You want to ensure timer.start() is not called before that variable is set to true. Or alternatively call timer.stop() just before it and restart it just after it

**Comment by wlbragg** [comment]
So maybe something like 

~~~
oil_consumption.simulatedTime = 1;
oil_consumption.start();
~~~

should look like this

~~~
if (oil_consumption) {
oil_consumption.stop();
}
oil_consumption.simulatedTime = 1;
oil_consumption.start();
~~~

**Comment by legoboyvdlp** [comment]
> if (oil_consumption.isRunning) {
oil_consumption.stop();
}


Should theoretically work, alternatively add == 1 to the if statement.

**Comment by wlbragg** [comment]
For sure the isRunning check to shut the timer off fixed the one error. But I have another inconsistent issue. This happened once after leaving the complex engine and failures checked.
~~~
  108.83 [ALRT]:nasal      Electrical system initialized
  108.83 [ALRT]:nasal      Astro Tech LC-2 Chronometer Loaded
  110.60 [ALRT]:nasal      Nasal runtime error: too few function args (have 0 need 2)
  110.60 [ALRT]:nasal        at 
  110.63 [ALRT]:nasal      Nasal runtime error: too few function args (have 0 need 2)
  110.63 [ALRT]:nasal        at 
  110.66 [ALRT]:nasal      Nasal runtime error: too few function args (have 0 need 2)
  110.66 [ALRT]:nasal        at 
  110.70 [ALRT]:nasal      Nasal runtime error: too few function args (have 0 need 2)
  110.70 [ALRT]:nasal        at 
  110.73 [ALRT]:nasal      Nasal runtime error: too few function args (have 0 need 2)
  110.73 [ALRT]:nasal        at 
  110.75 [ALRT]:nasal      Nasal runtime error: too few function args (have 0 need 2)
  110.75 [ALRT]:nasal        at 
  110.79 [ALRT]:nasal      Nasal runtime error: too few function args (have 0 need 2)
  110.79 [ALRT]:nasal        at 
  110.82 [ALRT]:nasal      Nasal runtime error: too few function args (have 0 need 2)
  110.82 [ALRT]:nasal        at 
  110.86 [ALRT]:nasal      Nasal runtime error: too few function args (have 0 need 2)
  110.86 [ALRT]:nasal        at 
  110.89 [ALRT]:nasal      Nasal runtime error: too few function args (have 0 need 2)
  110.89 [ALRT]:nasal        at 
  110.92 [ALRT]:nasal      Nasal runtime error: too few function args (have 0 need 2)
  110.92 [ALRT]:nasal        at 
  110.98 [ALRT]:nasal      Nasal runtime error: too few function args (have 0 need 2)
  110.98 [ALRT]:nasal        at 
  111.01 [ALRT]:nasal      Nasal runtime error: too few function args (have 0 need 2)
  111.01 [ALRT]:nasal        at 
  111.05 [ALRT]:nasal      Nasal runtime error: too few function args (have 0 need 2)
  111.05 [ALRT]:nasal        at 
  111.08 [ALRT]:nasal      Nasal runtime error: too few function args (have 0 need 2)
  111.08 [ALRT]:nasal        at 
  111.12 [ALRT]:nasal      Nasal runtime error: too few function args (have 0 need 2)
  111.12 [ALRT]:nasal        at 
  111.14 [ALRT]:nasal      Nasal runtime error: too few function args (have 0 need 2)
  111.14 [ALRT]:nasal        at 
  111.17 [ALRT]:nasal      Nasal runtime error: too few function args (have 0 need 2)
  111.17 [ALRT]:nasal        at 
  111.20 [WARN]:terrain    Path "/mnt/HDrive/FG/world-scenery/Terrain/w160n20/w156n20/400259.stg": Object at -155.5, 20.083 in incorrect bucket (-156:3, 20:0) - should be in 400260 (-156:4, 20:0)
  111.21 [ALRT]:nasal      Nasal runtime error: too few function args (have 0 need 2)
  111.21 [ALRT]:nasal        at 
  111.25 [ALRT]:nasal      Nasal runtime error: too few function args (have 0 need 2)
  111.25 [ALRT]:nasal        at 
  111.28 [ALRT]:nasal      Nasal runtime error: too few function args (have 0 need 2)
  111.28 [ALRT]:nasal        at 
  111.31 [ALRT]:nasal      Nasal runtime error: too few function args (have 0 need 2)
  111.31 [ALRT]:nasal        at 
  111.35 [ALRT]:nasal      Nasal runtime error: too few function args (have 0 need 2)
  111.35 [ALRT]:nasal        at 
  111.38 [ALRT]:nasal      Nasal runtime error: too few function args (have 0 need 2)
  111.38 [ALRT]:nasal        at 
  111.40 [ALRT]:nasal      Nasal runtime error: too few function args (have 0 need 2)
  111.40 [ALRT]:nasal        at 
  111.44 [ALRT]:nasal      Nasal runtime error: too few function args (have 0 need 2)
  111.44 [ALRT]:nasal        at 
  111.47 [ALRT]:nasal      Nasal runtime error: too few function args (have 0 need 2)
  111.48 [ALRT]:nasal        at 
  111.52 [ALRT]:nasal      Nasal runtime error: too few function args (have 0 need 2)
  111.52 [ALRT]:nasal        at 
  111.54 [ALRT]:nasal      Nasal runtime error: too few function args (have 0 need 2)
  111.54 [ALRT]:nasal        at 
  111.57 [ALRT]:nasal      Tile direction 0 not generated!
  111.57 [ALRT]:nasal      Flag: 0
  111.57 [ALRT]:nasal      Nasal runtime error: too few function args (have 0 need 2)
  111.57 [ALRT]:nasal        at 
  111.61 [ALRT]:nasal      Nasal runtime error: too few function args (have 0 need 2)
  111.61 [ALRT]:nasal        at 
  111.64 [ALRT]:nasal      Nasal runtime error: too few function args (have 0 need 2)
  111.64 [ALRT]:nasal        at 
  111.67 [ALRT]:nasal      Nasal runtime error: too few function args (have 0 need 2)
  111.67 [ALRT]:nasal        at 
  111.71 [ALRT]:nasal      Nasal runtime error: too few function args (have 0 need 2)
  111.71 [ALRT]:nasal        at 
  111.74 [ALRT]:nasal      Nasal runtime error: too few function args (have 0 need 2)
  111.74 [ALRT]:nasal        at 
  111.78 [ALRT]:nasal      Nasal runtime error: too few function args (have 0 need 2)
  111.78 [ALRT]:nasal        at 
  111.81 [ALRT]:nasal      Nasal runtime error: BUG: bad opcode
  111.84 [ALRT]:nasal      Nasal runtime error: BUG: bad opcode
  111.88 [ALRT]:nasal      Nasal runtime error: BUG: bad opcode
  111.90 [ALRT]:nasal      Nasal runtime error: BUG: bad opcode
  111.94 [ALRT]:nasal      Nasal runtime error: BUG: bad opcode
  111.98 [ALRT]:nasal      Nasal runtime error: BUG: bad opcode
  112.02 [ALRT]:nasal      Nasal runtime error: BUG: bad opcode
  112.04 [ALRT]:nasal      Nasal runtime error: BUG: bad opcode
  112.08 [ALRT]:nasal      Nasal runtime error: BUG: bad opcode
  112.11 [ALRT]:nasal      Nasal runtime error: BUG: bad opcode
  112.15 [ALRT]:nasal      Nasal runtime error: BUG: bad opcode
  112.17 [ALRT]:nasal      Nasal runtime error: BUG: bad opcode
  112.21 [ALRT]:nasal      Nasal runtime error: BUG: bad opcode
  112.24 [ALRT]:nasal      Nasal runtime error: BUG: bad opcode
  112.27 [ALRT]:nasal      Nasal runtime error: BUG: bad opcode
  112.31 [ALRT]:nasal      Nasal runtime error: BUG: bad opcode
  112.34 [ALRT]:nasal      Nasal runtime error: BUG: bad opcode
  112.37 [ALRT]:nasal      Nasal runtime error: BUG: bad opcode
  112.41 [ALRT]:nasal      Nasal runtime error: BUG: bad opcode
  112.45 [ALRT]:nasal      Nasal runtime error: BUG: bad opcode
  112.48 [ALRT]:nasal      Nasal runtime error: BUG: bad opcode
  112.50 [ALRT]:nasal      Nasal runtime error: BUG: bad opcode
  112.54 [ALRT]:nasal      Nasal runtime error: BUG: bad opcode
  112.58 [ALRT]:nasal      Nasal runtime error: BUG: bad opcode
  112.61 [ALRT]:nasal      Nasal runtime error: BUG: bad opcode
  112.64 [ALRT]:nasal      Nasal runtime error: BUG: bad opcode
  112.67 [ALRT]:nasal      Nasal runtime error: BUG: bad opcode
  112.71 [ALRT]:nasal      Nasal runtime error: BUG: bad opcode
  112.76 [ALRT]:nasal      Nasal runtime error: BUG: bad opcode
  112.79 [ALRT]:nasal      Nasal runtime error: BUG: bad opcode
  112.83 [ALRT]:nasal      Nasal runtime error: BUG: bad opcode
  112.85 [ALRT]:nasal      Nasal runtime error: BUG: bad opcode
  112.89 [ALRT]:nasal      Nasal runtime error: BUG: bad opcode
  112.92 [ALRT]:nasal      Nasal runtime error: BUG: bad opcode
  112.96 [ALRT]:nasal      Nasal runtime error: BUG: bad opcode
  112.99 [ALRT]:nasal      Nasal runtime error: BUG: bad opcode
  113.02 [ALRT]:nasal      Nasal runtime error: BUG: bad opcode
  113.06 [ALRT]:nasal      Nasal runtime error: BUG: bad opcode
  113.09 [ALRT]:nasal      Nasal runtime error: BUG: bad opcode
  113.12 [ALRT]:nasal      Nasal runtime error: BUG: bad opcode
  113.16 [ALRT]:nasal      Nasal runtime error: BUG: bad opcode
  113.19 [ALRT]:nasal      Nasal runtime error: BUG: bad opcode
  113.23 [ALRT]:nasal      Nasal runtime error: BUG: bad opcode
  113.28 [ALRT]:nasal      Nasal runtime error: BUG: bad opcode
  113.30 [ALRT]:nasal      Nasal runtime error: BUG: bad opcode
  113.32 [ALRT]:nasal      Nasal runtime error: BUG: bad opcode
  113.36 [ALRT]:nasal      Nasal runtime error: BUG: bad opcode
  113.41 [ALRT]:nasal      Nasal runtime error: BUG: bad opcode
  113.44 [ALRT]:nasal      Nasal runtime error: BUG: bad opcode
  113.48 [ALRT]:nasal      Nasal runtime error: BUG: bad opcode
  113.51 [ALRT]:nasal      Nasal runtime error: BUG: bad opcode
  113.54 [ALRT]:nasal      Nasal runtime error: BUG: bad opcode
  113.57 [ALRT]:nasal      Nasal runtime error: BUG: bad opcode
  113.61 [ALRT]:nasal      Nasal runtime error: BUG: bad opcode
  113.64 [ALRT]:nasal      Nasal runtime error: BUG: bad opcode
  113.68 [ALRT]:nasal      Nasal runtime error: BUG: bad opcode
  113.71 [ALRT]:nasal      Nasal runtime error: BUG: bad opcode
  113.74 [ALRT]:nasal      Nasal runtime error: BUG: bad opcode
  113.78 [ALRT]:nasal      Starter on
  113.78 [ALRT]:nasal      Nasal runtime error: BUG: bad opcode
  113.82 [ALRT]:nasal      Nasal runtime error: BUG: bad opcode
  113.86 [ALRT]:nasal      Nasal runtime error: BUG: bad opcode
  113.89 [ALRT]:nasal      Nasal runtime error: BUG: bad opcode
  113.99 [ALRT]:nasal      Nasal runtime error: BUG: bad opcode
  114.05 [ALRT]:nasal      Nasal runtime error: BUG: bad opcode
  114.08 [ALRT]:nasal      Nasal runtime error: BUG: bad opcode
  114.13 [ALRT]:nasal      Nasal runtime error: BUG: bad opcode
  114.18 [ALRT]:nasal      Nasal runtime error: BUG: bad opcode
  114.23 [ALRT]:nasal      Nasal runtime error: BUG: bad opcode
  114.28 [ALRT]:nasal      Nasal runtime error: BUG: bad opcode
  114.33 [ALRT]:nasal      Nasal runtime error: BUG: bad opcode
  114.38 [ALRT]:nasal      Nasal runtime error: BUG: bad opcode
  114.43 [ALRT]:nasal      Nasal runtime error: BUG: bad opcode
  114.48 [ALRT]:nasal      Nasal runtime error: BUG: bad opcode
  114.53 [ALRT]:nasal      Nasal runtime error: BUG: bad opcode
  114.58 [ALRT]:nasal      Nasal runtime error: BUG: bad opcode
  114.63 [ALRT]:nasal      Nasal runtime error: BUG: bad opcode
  114.69 [ALRT]:nasal      Nasal runtime error: BUG: bad opcode
  114.73 [ALRT]:nasal      Nasal runtime error: BUG: bad opcode
  114.78 [ALRT]:nasal      Nasal runtime error: BUG: bad opcode
  114.83 [ALRT]:nasal      Nasal runtime error: BUG: bad opcode
  114.88 [ALRT]:nasal      Nasal runtime error: BUG: bad opcode
  114.93 [ALRT]:nasal      Nasal runtime error: BUG: bad opcode
  114.98 [ALRT]:nasal      Nasal runtime error: BUG: bad opcode
  115.03 [ALRT]:nasal      Nasal runtime error: BUG: bad opcode
  115.08 [ALRT]:nasal      Nasal runtime error: BUG: bad opcode
  115.12 [ALRT]:nasal      Nasal runtime error: BUG: bad opcode
  115.18 [ALRT]:nasal      Nasal runtime error: BUG: bad opcode
  115.25 [ALRT]:nasal      Nasal runtime error: BUG: bad opcode
  115.29 [ALRT]:nasal      Nasal runtime error: BUG: bad opcode
  115.35 [ALRT]:nasal      Nasal runtime error: BUG: bad opcode
  115.39 [ALRT]:nasal      Nasal runtime error: BUG: bad opcode
  115.44 [ALRT]:nasal      Nasal runtime error: BUG: bad opcode
  115.48 [ALRT]:nasal      Nasal runtime error: BUG: bad opcode
  115.54 [ALRT]:nasal      Nasal runtime error: BUG: bad opcode
  115.58 [ALRT]:nasal      Tile direction 0 not generated!
  115.58 [ALRT]:nasal      Flag: 0
  115.58 [ALRT]:nasal      Nasal runtime error: BUG: bad opcode
  115.64 [ALRT]:nasal      Nasal runtime error: BUG: bad opcode
  115.68 [ALRT]:nasal      Nasal runtime error: BUG: bad opcode
  115.73 [ALRT]:nasal      Nasal runtime error: BUG: bad opcode
  115.78 [ALRT]:nasal      Nasal runtime error: BUG: bad opcode
  115.83 [ALRT]:nasal      Nasal runtime error: BUG: bad opcode
  115.88 [ALRT]:nasal      Nasal runtime error: BUG: bad opcode
  115.93 [ALRT]:nasal      Nasal runtime error: BUG: bad opcode
  115.98 [ALRT]:nasal      Nasal runtime error: BUG: bad opcode
  116.03 [ALRT]:nasal      Hobbs system started
  116.03 [ALRT]:nasal      Nasal runtime error: BUG: bad opcode
  116.08 [ALRT]:nasal      Nasal runtime error: BUG: bad opcode
  116.13 [ALRT]:nasal      Nasal runtime error: BUG: bad opcode
  116.18 [ALRT]:nasal      Nasal runtime error: BUG: bad opcode
  116.23 [ALRT]:nasal      Nasal runtime error: BUG: bad opcode
  116.28 [ALRT]:nasal      Nasal runtime error: BUG: bad opcode
  116.33 [ALRT]:nasal      Nasal runtime error: BUG: bad opcode
  116.38 [ALRT]:nasal      Nasal runtime error: BUG: bad opcode
  116.42 [ALRT]:nasal      Nasal runtime error: BUG: bad opcode
  116.48 [ALRT]:nasal      Nasal runtime error: BUG: bad opcode
  116.53 [ALRT]:nasal      Nasal runtime error: BUG: bad opcode
  116.58 [ALRT]:nasal      Nasal runtime error: BUG: bad opcode
Segmentation fault
~~~
The procedure that caused it was to start the tutorial with the "complex engine and failures" checked.
I'm wondering if we shouldn't be turning that off in the tutorial. Funny thing is the next several times I tried to stop the sim and start it again and then start the tutorial it was fine. Then I stopped the tutorial through the GUI and started it back up without getting out of the sim and it worked without error. So this other segfault error is inconsistent.

@gilbertohasnofb I can confirm that your change did fix the cowl plug problem however.

I recommend we do the isRunning check to shut the off the timer if it is running. I think it is important because not only the tutorials can fail from this the re-init on airport relocation can as well.
I use c172p.oil_consumption.stop(); in the save/resume code and the mooring relocation code to eliminate that error. But we have no way to execute that for the tutorial or the airport relocation early enough for it to work.

**Comment by wlbragg** [comment]
I just checked the airport relocation in the GUI and I still get inconsistent segfaults. The only error I see, sometimes is...
~~~
  109.20 [ALRT]:nasal      Nasal runtime error: BUG: bad opcode
  109.20 [ALRT]:nasal        at 
  109.24 [ALRT]:nasal      Nasal runtime error: BUG: bad opcode
  109.24 [ALRT]:nasal        at 
  109.30 [ALRT]:nasal      Nasal runtime error: BUG: bad opcode
  109.30 [ALRT]:nasal        at 
  109.35 [ALRT]:nasal      Nasal runtime error: BUG: bad opcode
  109.35 [ALRT]:nasal        at 
  109.41 [ALRT]:nasal      Nasal runtime error: BUG: bad opcode
  109.41 [ALRT]:nasal        at 
  109.44 [ALRT]:nasal      Nasal runtime error: BUG: bad opcode
  109.44 [ALRT]:nasal        at 
  109.50 [ALRT]:nasal      Nasal runtime error: BUG: bad opcode
  109.50 [ALRT]:nasal        at 
  109.61 [ALRT]:nasal      Nasal runtime error: BUG: bad opcode
  109.61 [ALRT]:nasal        at 
  109.65 [ALRT]:nasal      Nasal runtime error: BUG: bad opcode
  109.65 [ALRT]:nasal        at 
  109.69 [ALRT]:nasal      Nasal runtime error: BUG: bad opcode
  109.69 [ALRT]:nasal        at 
  109.73 [ALRT]:nasal      Nasal runtime error: BUG: bad opcode
  109.73 [ALRT]:nasal        at 
  109.79 [ALRT]:nasal      Nasal runtime error: BUG: bad opcode
  109.79 [ALRT]:nasal        at 
  109.83 [ALRT]:nasal      Nasal runtime error: BUG: bad opcode
  109.83 [ALRT]:nasal        at 
  109.93 [ALRT]:nasal      Nasal runtime error: BUG: bad opcode
  109.93 [ALRT]:nasal        at 
  109.98 [ALRT]:nasal      Nasal runtime error: BUG: bad opcode
  109.98 [ALRT]:nasal        at 
  110.04 [ALRT]:nasal      Nasal runtime error: BUG: bad opcode
  110.04 [ALRT]:nasal        at 
  110.10 [ALRT]:nasal      Nasal runtime error: BUG: bad opcode
  110.10 [ALRT]:nasal        at 
  110.14 [ALRT]:nasal      Nasal runtime error: BUG: bad opcode
  110.14 [ALRT]:nasal        at 
  110.17 [ALRT]:nasal      Nasal runtime error: BUG: bad opcode
  110.17 [ALRT]:nasal        at 
  110.23 [ALRT]:nasal      Nasal runtime error: BUG: bad opcode
  110.23 [ALRT]:nasal        at 
  110.28 [ALRT]:nasal      Nasal runtime error: BUG: bad opcode
  110.28 [ALRT]:nasal        at 
  110.32 [ALRT]:nasal      Nasal runtime error: BUG: bad opcode
  110.32 [ALRT]:nasal        at 
  110.40 [ALRT]:nasal      Nasal runtime error: BUG: bad opcode
  110.40 [ALRT]:nasal        at 
  110.42 [ALRT]:nasal      Nasal runtime error: BUG: bad opcode
  110.42 [ALRT]:nasal        at 
  110.49 [ALRT]:nasal      Nasal runtime error: BUG: bad opcode
  110.49 [ALRT]:nasal        at 
  110.52 [ALRT]:nasal      Nasal runtime error: BUG: bad opcode
  110.52 [ALRT]:nasal        at 
  110.62 [ALRT]:nasal      Nasal runtime error: BUG: bad opcode
  110.62 [ALRT]:nasal        at 
  110.64 [ALRT]:nasal      Nasal runtime error: BUG: bad opcode
  110.64 [ALRT]:nasal        at 
  110.68 [ALRT]:nasal      Nasal runtime error: BUG: bad opcode
  110.68 [ALRT]:nasal        at 
  110.74 [ALRT]:nasal      Nasal runtime error: BUG: bad opcode
  110.74 [ALRT]:nasal        at 
  110.78 [ALRT]:nasal      Nasal runtime error: BUG: bad opcode
  110.78 [ALRT]:nasal        at 
  110.83 [ALRT]:nasal      Nasal runtime error: BUG: bad opcode
  110.83 [ALRT]:nasal        at 
  110.92 [ALRT]:nasal      Nasal runtime error: BUG: bad opcode
  110.92 [ALRT]:nasal        at 
  110.96 [ALRT]:nasal      Nasal runtime error: BUG: bad opcode
  110.96 [ALRT]:nasal        at 
  110.99 [ALRT]:nasal      Nasal runtime error: BUG: bad opcode
  110.99 [ALRT]:nasal        at 
  111.09 [WARN]:ai         Gate Parking_GA_P3/Parking_GA_P3 at EBCI doesn't seem to have routes associated with it.
  111.09 [ALRT]:nasal      Nasal runtime error: BUG: bad opcode
  111.09 [ALRT]:nasal        at 
  111.12 [ALRT]:nasal      Nasal runtime error: BUG: bad opcode
  111.12 [ALRT]:nasal        at 
  111.16 [ALRT]:nasal      Nasal runtime error: BUG: bad opcode
  111.16 [ALRT]:nasal        at 
  111.23 [ALRT]:nasal      Nasal runtime error: BUG: bad opcode
  111.23 [ALRT]:nasal        at 
  111.29 [ALRT]:nasal      Nasal runtime error: BUG: bad opcode
  111.29 [ALRT]:nasal        at 
  111.34 [ALRT]:nasal      Nasal runtime error: BUG: bad opcode
  111.34 [ALRT]:nasal        at 
  111.40 [ALRT]:nasal      Nasal runtime error: BUG: bad opcode
  111.40 [ALRT]:nasal        at 
  111.43 [ALRT]:nasal      Nasal runtime error: BUG: bad opcode
  111.43 [ALRT]:nasal        at 
  111.46 [ALRT]:nasal      Nasal runtime error: BUG: bad opcode
  111.46 [ALRT]:nasal        at 
  111.51 [ALRT]:nasal      Nasal runtime error: BUG: bad opcode
  111.51 [ALRT]:nasal        at 
  111.58 [ALRT]:nasal      Nasal runtime error: BUG: bad opcode
  111.58 [ALRT]:nasal        at 
  111.62 [ALRT]:nasal      Nasal runtime error: BUG: bad opcode
  111.62 [ALRT]:nasal        at 
  111.66 [ALRT]:nasal      Nasal runtime error: BUG: bad opcode
  111.66 [ALRT]:nasal        at 
  111.72 [ALRT]:nasal      Nasal runtime error: BUG: bad opcode
  111.72 [ALRT]:nasal        at 
  111.76 [ALRT]:nasal      Nasal runtime error: BUG: bad opcode
  111.76 [ALRT]:nasal        at 
  111.81 [ALRT]:nasal      Tile direction 0 not generated!
  111.81 [ALRT]:nasal      Flag: 0
  111.87 [ALRT]:nasal      Nasal runtime error: BUG: bad opcode
  111.87 [ALRT]:nasal        at 
  112.11 [ALRT]:nasal      Nasal runtime error: BUG: bad opcode
  112.11 [ALRT]:nasal        at 
  112.20 [ALRT]:nasal      Nasal runtime error: BUG: bad opcode
  112.20 [ALRT]:nasal        at 
  112.28 [ALRT]:nasal      Nasal runtime error: BUG: bad opcode
  112.28 [ALRT]:nasal        at 
  112.34 [ALRT]:nasal      Nasal runtime error: BUG: bad opcode
  112.34 [ALRT]:nasal        at 
  112.39 [ALRT]:nasal      Nasal runtime error: BUG: bad opcode
  112.39 [ALRT]:nasal        at 
  112.44 [ALRT]:nasal      Nasal runtime error: BUG: bad opcode
  112.44 [ALRT]:nasal        at 
Segmentation fault
~~~
But using the isRunning check for the oil timer is eliminating that nasal error and segfault.

**Comment by wlbragg** [comment]
I don't know what the correct answer for this is. I'm wondering if we shouldn't be paying more attention to timers and how re-init affects them. Maybe this is a discussion for the dev list.

**Comment by gilbertohasnofb** [comment]
> I can confirm that your change did fix the cowl plug problem however.

That's good, that was an easy fix. The tutorials weren't enforcing the plugs to be off. It wasn't just the taxiing tutorial but all of them. If we ever add more items to the pre-flight inspection, we need to make sure that all tutorials are updated properly.

But as for the timer issue, I am really puzzled by this. Is our `master` broken then? Because this PR was created on a clean new branch based on the current `master`. I would say that if this PR fixes the issue of cowl plugs and adds no new breaks then we can merge it and then work on these timer issues in a separate branch.

Also, do you guys know what commit introduced these issues?

**Comment by wlbragg** [comment]
I don't know what introduced any of this other than I for sure get this error (top three lines)
~~~
77.02 [ALRT]:nasal      Nasal runtime error: Timer is running, cannot change type between real/sim time
   77.02 [ALRT]:nasal        at /mnt/GDrive/Aircraft/Development Aircraft/c172p/Nasal/engine.nas, line 500
   77.02 [ALRT]:nasal        called from: /home/wayne/FGFS/install/flightgear/fgdata/Nasal/globals.nas, line 119
   77.02 [ALRT]:nasal      Electrical system initialized
   77.02 [ALRT]:nasal      Astro Tech LC-2 Chronometer Loaded
   82.02 [ALRT]:nasal      Starter on
   83.89 [ALRT]:nasal      Nasal runtime error: too few function args (have 0 need 14)
   83.89 [ALRT]:nasal        at 
Segmentation fault
~~~
which eventually always leads to a segfault on every re-init unless accounted for (as I do in the mooring and save/resume code or unless I use what @legoboyvdlp suggested, see https://github.com/c172p-team/c172p/pull/1266/commits/3c4e8d70d2a99dd7a908e3e6aa582a1e4d0c20f9

But I still intermittently get https://github.com/c172p-team/c172p/pull/1266#issuecomment-478203264 even with the timer check. But i think that is a different issue.

**Comment by gilbertohasnofb** [comment]
@wlbragg Have any of you brought this issue up in the dev list? Is it a FG issue or is it a problem with our aircraft? Regardless, we could merge this if it fixes the bug in question

**Comment by wlbragg** [comment]
I think it is more a FG issue as it is a problem with how the timers are handled on a re-init. But it is something we aircraft developers can potentially mitigate if we are aware of the issue and tailor our code to handle re-inits.
I don't know what is causing the following error, so I really don't know what's more at fault, FG or us.
At any rate, yes, I think we can go ahead and merge this PR and the remaining issue is really already touched upon in this https://github.com/c172p-team/c172p/issues/1265 issue.

**Comment by gilbertohasnofb** [comment]
> At any rate, yes, I think we can go ahead and merge this PR

So then please do it :smile: 

> I think it is more a FG issue as it is a problem with how the timers are handled on a re-init. But it is something we aircraft developers can potentially mitigate if we are aware of the issue and tailor our code to handle re-inits.

I see. I just don't remember ever coming across it before, but possibly I wasn't paying attention to it.

**Comment by wlbragg** [comment]
This error I have seen many times in different attempts to do a re-init. It is related to the oil timer. The commit i made here accounts for it.
~~~
77.02 [ALRT]:nasal      Nasal runtime error: Timer is running, cannot change type between real/sim time
   77.02 [ALRT]:nasal        at /mnt/GDrive/Aircraft/Development Aircraft/c172p/Nasal/engine.nas, line 500
   77.02 [ALRT]:nasal        called from: /home/wayne/FGFS/install/flightgear/fgdata/Nasal/globals.nas, line 119
~~~

This one
~~~
Nasal runtime error: too few function args (have 0 need 14)
   83.89 [ALRT]:nasal        at 
~~~
I still get and I think it is a new error. I don't know what it is. I am a bit concerned that no one else is confirming any of these errors. Am I the only one getting these?

**Comment by wkitty42** [comment]
> I am a bit concerned that no one else is confirming any of these errors. Am I the only one getting these?

FWIW: unfortunately, i'm not able to test FG at this time... something with it or in combination with something else causes my systems to power off with no warning at all... not a proper shutdown... complete power off... boom! lights out! when it happens, i have to unplug the power cable for a few seconds, plug it back in and then boot the machine... i'm seeing this on two different OS installs on different MBs with different RAM and HDs and have not been able to find the problem...

**Comment by wlbragg** [comment]
@wkitty42 
It's FG specific?
It's c172p specific?

**Comment by wkitty42** [comment]
On 3/31/19 3:04 PM, wlbragg wrote:
> @wkitty42
> It's FG specific?
> It's c172p specific?

it happens in the UFO so nothing related to our craft...

**Pull request merged**
