### PR TITLE
new flaps motor sound

### LINKED ISSUE #1171: Improve flap sound
- separate flap lever (click) and motor sounds (you could move the lever without electrical power, and that should make a click)
- find a new motor sound - I found a public domain one somewhere from a Cessna but never could find it again, it is an electrical whining noise if i recall correctly. YouTube might help to compare any sounds you find against.

If nobody beats me to it I'll have a search for sounds and if possible implement this.

### PR DESCRIPTION
**Pull request by gilbertohasnofb**
Fixes #1171 

This PR only changes the flaps motor sound and is ready to be merged. To test it, compare the new sound to the second and third sounds from the reference link below:

https://www.soundsnap.com/tags/cessna?page=1

Also test that the flaps motor sounds good throughout it's playback time by lowering the flaps from 0 to 40 degrees.

### CODE REVIEW

**Comment by wlbragg** [comment]
@gilbertohasnofb I like it, sound really good. Having not been in the real thing in over 50 years I couldn't tell you if it sounds like the real thing, but it sure does sound like a slow speed electrical motor.

I take it someone on this project is a member of soundsnap?

I looked over the license, have we used this source before on any other aircraft?

Did you alter the sound at all?

**Comment by gilbertohasnofb** [comment]
> I take it someone on this project is a member of soundsnap?

@wlbragg Oh, you misunderstood what I did. I used their sound as an aural reference only (that is I just listened to it) since it is a recording of the real thing. But my sound does not use that as source at all, it was created using CC0 and using sound design techniques: my sound is composite of a generic motor pitched up a lot and mixed with a vacuum cleaner sound, all with a high pass filter to remove low frequency noises. Most of the sounds I create have to be done in this way. This is clean CC0 derivative work.

**Comment by gilbertohasnofb** [comment]
No worries. So this is ready to be merged if you think it works well. Later today I will check your new commits in those other PRs.

**Comment by legoboyvdlp** [comment]
@gilbertohasnofb it's a little late now, but the only thing I would have suggested is reduce the pitch (frequency) of the sound in your sound editor slightly to match the pitch of the aural reference. The sound is great, just maybe a little high pitched. Not really that important though.

**Comment by gilbertohasnofb** [comment]
@legoboyvdlp done.

@onox my apologies but I ended up pushing the pitched down sound directly to the master... I restored the branch above but pushed my commit to the master without realizing. Do you want me to undo that or can we live with this one? It's just a small change in pitch to the sound. This is the commit: https://github.com/c172p-team/c172p/commit/849e3f1e0fb930b66c80bf72954e9fbfad5622f3

**Comment by onox** [comment]
We can live with it.

**Comment by gilbertohasnofb** [comment]
Thanks!

**Pull request merged**
