### PR TITLE
Bugs in view logic and fuel priority

### LINKED ISSUE #1373: Mouse scroll to change zoom doesn't work anymore.
As the title says. You can no longer change FOV with the mouse wheel.

### LINKED ISSUE #1374: External views break when switching airports.
External views, such as Helicopter View and others, break when you use Select Airport in sim, to go to a different airport.
Might be related to #1373 

Video showing the issue.
https://www.youtube.com/watch?v=5acOygRYRUg
Or, if you prefer, on Odysee.
https://odysee.com/FlightGear_Camera_Bug_Demonstration

### PR DESCRIPTION
**Pull request by wlbragg**
Fixes #1374
Fixes #1373

@legoboyvdlp Once merged these also need cherry picked into release 2020.3. I verified your first cherry pick it looks fine.

I'm tired of making issues for a simple bug fix so I am adding the fuel bug to this, this I changed the name. See the discussion at https://forum.flightgear.org/viewtopic.php?f=66&t=39392 if you have any questions as to why I changed it again. The PR you merged the other day technically fixe it but it didn't need all the superfluous code.

This is ready to go.

### CODE REVIEW

**Comment by legoboyvdlp** [comment]
Interesting. I relocated from SVVP to EGAA, when I did that, the gear reactions seemed to break, because at that point the aircraft simply refused to move. 


Regardless; these two bugs are fixed - the aircraft engine will die when you crash and the view bugs are fixed.

**Comment by wlbragg** [comment]
Thanks, did you wait long enough after relocating? This is important to know if that bug is still there. It takes a few seconds after its back up after a relocate for the gear to release and the aircraft to move. If it did lock up then I know what the bug is and I will figure out how to fix it.

**Comment by Megaf** [comment]
Doesn't fix #1373

**Comment by legoboyvdlp** [comment]
I checked it specifically, and when I scrolled the zoom changed. So not sure why not.

**Pull request merged**
