### PR TITLE
Correct light maps on instrument cases

### LINKED ISSUE #1185: Modify light maps on instrument cases
The light map covering the case face on the instrument is not correct, it is too dark.

### PR DESCRIPTION
**Pull request by wlbragg**
Fixes #1185

@gilbertohasnofb 

:warning::warning::warning:
PLEASE  MERGE AFTER New Aero Tech LC-2 digital clock #1183 
 :warning::warning::warning:

### CODE REVIEW

**Comment by wlbragg** [comment]
This also correct some bad uv mapping on the clock and battery gauges as well as correcting their light maps.

@gilbertohasnofb  this is ready to merge ASAP!

Having different PR's all dealing with some of the same mesh pieces is making this more difficult than it needs to be. Specifically the lm.blend and digital clock VS no digital clock differences in the lm.blend.
I just need this and the clock PR merged so I can start working on a non fragmented master.

I am putting the same lm.blend in both this PR and the digital clock PR so one doesn't overwrite the other, or at least they will overwrite them with the same version.

It's getting difficult to juggle and taking me much longer to get stuff done.

**Comment by wlbragg** [comment]
Much better I think...
Post lighting
lm1

Overhead dome lighting
lm3

No lighting
lm2

**Comment by wlbragg** [comment]
@gilbertohasnofb this is ready to merge!

:warning::warning::warning:
PLEASE  MERGE AFTER New Aero Tech LC-2 digital clock #1183 
 :warning::warning::warning:

You will more than likely get a merge conflict with lm.blend. It is OK for this version of lm.blend to overwrite what ever is in the master repository. This is the most current lm.blend.

**Comment by gilbertohasnofb** [comment]
@wlbragg I tested t his and this looks good but indeed there is a merge conflict pending. Could you please solve this? There is no way of doing it via the web editor since .blend files aren't editible and differentiable. You will likely need to manually replace the file and push it as to match the current master.

**Comment by gilbertohasnofb** [comment]
@wlbragg thanks!

**Pull request merged**
