### PR TITLE
Reshape and widen 26" and 36" bush tires to 12" and 15"

### LINKED ISSUE #1230: Widen and reshape 26" and 36" bush tires
The 26" and 36" tires are too narrow. This PR widens them to 12" and 15" respectively.
It also reshapes them to be more like balloon tires.

### PR DESCRIPTION
**Pull request by wlbragg**
Fixes #1230 

This should be ready to merge after review.

This brings the bush tires 26" and 36" to the advertised sizes of 26x12 and 36x15.
I also reshaped them to be more like balloon tires.

### CODE REVIEW

**Comment by legoboyvdlp** [comment]
I'll check and merge.

**Comment by wlbragg** [comment]
@legoboyvdlp I know exactly what you mean and your right. It's using the same texture. What would be nice is a more rubbery texture like a balloon tire is made of.
A little more slick and shiny.

**Comment by legoboyvdlp** [comment]
image

image

some reference images

**Comment by wlbragg** [comment]
The top one's are slicks and the bottom one looks treaded.
I definitely want the 36" to be slicks. It would be nice if the 26" were treaded.

**Comment by wlbragg** [comment]
I went back into the blend and made some mapping changes. I think I have want we need already so @gilbertohasnofb no need of more texture work.
The mapping was slightly off center and I had already adjusted the mapping on the 36" tires to be slicks but was inaccurate an was still including a tread line in the mapping. I'll push a much better mapping here shortly.

**Comment by wlbragg** [comment]
OK, this is as good as I can do with existing textures. There are many more slight adjustments than meets the eyes.
The 36" tires are balloon tires and the 26" tires are meant to still be treaded tires.

**Comment by gilbertohasnofb** [comment]
@legoboyvdlp take a look and see if you like the new modifications, if so please merge this. Else I can do some retexturing when I am back,

**Comment by legoboyvdlp** [comment]
I like the look of these wheels. I have to say though, I think the 36" tyres still look a bit flat, a bit of texture work if you could do any would go a long way 😉 
image

**Comment by gilbertohasnofb** [comment]
I just took a look at this and the textures seem fine to me, what exactly would you need to change? IMO, this is basically ready to merge, except for the bug below: the smaller bush tire look good but the larger one is shiny, I think the material is messed up. Compare the images:

fg-0
fg-1

**Comment by legoboyvdlp** [comment]
I think I was seeing the reflection of the clouds in the tyre which made me think the textures were the problem :joy:

If that's fixed I think this can be merged.

**Comment by wlbragg** [comment]
This is done then and ready to merge. I lowered the shininess effect to darken the tire a bit. I purposely wanted the balloon tires to be a little more shiny than the other tires.

**Comment by gilbertohasnofb** [comment]
@wlbragg Thanks, it looks much better now.

**Pull request merged**
