### PR TITLE
Regress removal of fdm-init listener portion of commit a552abb

### LINKED ISSUE #1274: Nasal error in tiedowns
@wlbragg @gilbertohasnofb 

`Nasal runtime error: No such member: end_point
  139.56 [ALRT]:nasal        at C:/Users/redpa/Documents/FlightGear/Custom Aircraft/c172p/Nasal/tiedowns.nas, line 112
  139.56 [ALRT]:nasal        called from: C:/Users/redpa/Documents/FlightGear/Custom Aircraft/c172p/Nasal/tiedowns.nas, line 93
  139.57 [ALRT]:nasal        called from: C:/Users/redpa/Documents/FlightGear/Custom Aircraft/c172p/Nasal/tiedowns.nas, line 142
  139.57 [ALRT]:nasal        called from: C:/Users/redpa/Documents/Programs/FlightGear 2018.3.0/data/Nasal/globals.nas,`

In tiedowns.nas, `me.end_point` has no default value.

### PR DESCRIPTION
**Pull request by wlbragg**
Fixes #1274 

I think this is fixed.

@legoboyvdlp please confirm before merging. Once merged we can cherry pick it to the release.

### CODE REVIEW

**Comment by gilbertohasnofb** [comment]
@legoboyvdlp can you test and merge this please?

**Comment by legoboyvdlp** [comment]
Absolutely; I'll be home shortly and can do it then.

**Comment by gilbertohasnofb** [comment]
no rush, I am just pinging you in case you missed this PR

**Comment by onox** [comment]
Should this fix be backported to a release branch?

**Comment by wlbragg** [comment]
Yes

**Pull request merged**
