### PR TITLE
Fix pitch oscillations at rest, Brakes ON, with pure crosswind

### LINKED ISSUE #1297: Strong pitch oscillations at rest, Brakes "ON", with pure crosswind
Connected to:
- this remark by @algefean https://github.com/c172p-team/c172p/issues/1130#issuecomment-399561812
- this one, https://github.com/c172p-team/c172p/issues/1130#issuecomment-403204924
 and 
- this issue (description, investigation and circumventing solution) in JSBSim https://github.com/JSBSim-Team/jsbsim/issues/89

Very rare, we were the first ones to notice it. It happens with a pure crosswind (less than +/- 1 deg, about), aircraft at rest, brakes "ON". Every JSBSim aircraft is potentially affected, but our C172p is more sensitive due to its implemented gear damage possibility.
All the more unlikely that this occurence is almost impossible in flight.

The conclusion was that it was due to an imperfection and a divergence in a JSBSim calculation.

After careful investigation, @bcoconni found no true solution, but he proposed a circumventing which works. However, this change is not in the JSBSim core code, it has to be applied to every affected aircraft. Fortunately, the change is very easy to add in.

### PR DESCRIPTION
**Pull request by dany93**
Fixes #1297

### CODE REVIEW

**Comment by wlbragg** [comment]
I haven't applied this to the Cub yet but I verified this fixes the issue in the c172p so I am merging it now.

**Comment by dany93** [comment]
Thank you, @wlbragg

**Comment by wlbragg** [comment]
@dany93
Sorry it took me so long to test and merge. I just applied the fix to the Cub as well, works perfectly. Nice fix, thank you!

**Comment by dany93** [comment]
And thank you too @bcoconni for the code investigation and the explanations..

**Pull request merged**
