### PR TITLE
Add REV mode to KAP140

### LINKED ISSUE #1344: Add REV mode to the KAP140
There is a fix by @hbeni to the KAP140 on the c182s/t. All that is needed is to test and merge the newly created PR.
It needs to be tested by someone familiar with KAP140 operations before merging.

### PR DESCRIPTION
**Pull request by wlbragg**
Fixes #1344 

This adds a REV mode to the KAP140. From the c182s/t and @hbeni thank you.
Needs tested by someone familiar with KAP140 operations.

### CODE REVIEW

**Review by hbeni — APPROVED** [review]
Checked positive! :ok:

**Comment by legoboyvdlp** [comment]
Are we looking to merge this or replace it with something else such as the new KAP140 in the PA28?

**Comment by wlbragg** [comment]
It's going to be replaced with c182s implementation when they are finished.

**Comment by hbeni** [comment]
@wlbragg I think we can close this one, as it will be superseeded by implementing #1302 (Upgrade KAP-140 to new version)

**Comment by wlbragg** [comment]
@hbeni I'll be away until late afternoon. I'll look over everything you did and take actions then. Thank you so much for the help.

**Comment by wlbragg** [comment]
Superseded by implementing #1302 (Upgrade KAP-140 to new version)

**Pull request closed without merging**
