### PR TITLE
Issue 1124

### PR DESCRIPTION
**Pull request by legoboyvdlp**
Add digital clock: #1124

### CODE REVIEW

**Comment by gilbertohasnofb** [comment]
@legoboyvdlp this commit history is a mess, lego! :scream:

**Comment by legoboyvdlp** [comment]
I know - that is the problem with forks 😂

**Comment by wlbragg** [comment]
@legoboyvdlp 
I have employed the use of "git stash" and "git apply" and there is also the one @onox showed us but I can never remember it so I mostly use "stash/apply". When you need to update your branch you "stash" your current work and then after you pull and merge you "apply". I also mostly use "Git GUI", there is a feature that lets you add those commands under "Tools".

**Comment by wlbragg** [comment]
After reading @gilbertohasnofb comments in another thread, I am not positive this will help you.

**Comment by algefaen** [comment]
You can also maintain a cleaner history by using `git rebase`, as long as you're not re-writing history that you've already shared with others. Hint: `git pull -r` does the same as pull, just rebasing instead of creating merge commits.

**Comment by wlbragg** [comment]
git rebase that's the one, what so hard about that to remember? I always wondered if I had to use any other commands with it. So for example using "GIT GUI" if I were to make a "tool" that effectively did "git pull -r", even if I had committed to my local branch, I could pull changed and place my commits in order?
Sounds simple enough, thanks.

**Comment by legoboyvdlp** [comment]
@algefaen would you have any idea how to rebase it now that I have pushed these merge commits?

Or - you could do this:
create a new branch in c172p-team/c172p: issue-1124
pull the commits from my branch

run 
`git checkout interior-updates
git cherry-pick 0bc70d8
git cherry-pick b0edb52`

This **should** bring only the two important commits from my branch
Please check with someone more experienced (onox? algefaen?) before doing this ;)

**Comment by gilbertohasnofb** [comment]
@legoboyvdlp alternatively, given how simple these commits are, you can simply copy your files to a safe place (make sure you copy everything) and then delete your branch and close this PR. Then create a new branch based on whatever you want and start again.

**Comment by legoboyvdlp** [comment]
Problem is, my interior-updates branch is the one where all these merge commits are. So, I think I want to clean up that branch first then redo this pull request?

Or if it is easier for someone with push access here to just do the two cherry picks from branch issue 1124 to interior-updates?

If so I can write the commands needed tonight.

**Comment by gilbertohasnofb** [comment]
@legoboyvdlp one more thing, I noticed that you use the folder `clock` for both clocks. Don't do that, keep one model per folder please as all other models have individual folders. Perhaps `digital-clock` would be better.

**Comment by wlbragg** [comment]
@legoboyvdlp 
"IN THE FUTURE", to prevent this (bold is to make sure you understand this for future work and doesn't apply to cleaning this up).

If you have local changes you haven't committed locally yet and no local commits, use...

git stash
git pull
git apply

If you have no local uncommitted changes but you have local commits that haven't been pushed, use...

git pull -r 

If you have some local uncommitted changes and some local committed changes both that have not been pushed, use...

git stash
git pull -r 
git apply

I just tested this and it appeared to work as I expected.

Barring no other feedback or solution, I think I would go with @gilbertohasnofb suggestion and...
save your work, 
delete your branch,
make a new one from interior-updates,
add your changes,
request a merge to interior-updates.

And it anything changes in interior-updates before you request the merge, use my suggested steps above to get those changes depending on the state of your branch at the time.

After you make the request I can merge it into interior updates and apply all the effects to it.

If you want to learn how to add those effects yourself, at least the xml portion, let me know and I can walk you through it. Adding the instrument to the lm.blend is not so simple, there are a few steps and then the baking is complicated because of all the different issues we have.

**Comment by legoboyvdlp** [comment]
Ok - can do :)

However - the problem is, when I pull from here to another fork, it creates these merge commits. That's the source of all this mess in the commit history. I'm not sure how to avoid that. 

Anyway, I'll do this tomorrow. As for adding the effects, I can do the XML part, sure, but it would make merging more difficult as it would require you baking to avoid the various issues. That's why I suggested originally to push the files to here in a pull request, then let you bake the lightmaps. But regardless let me know which is easiest for you. I'm happy doing it if it's easier.

**Comment by wlbragg** [comment]
>However - the problem is, when I pull from here to my fork, it creates these merge commits. That's the source of all this mess in the commit history. I'm not sure how to avoid that.

If I stash my uncommitted work before a pull then apply, I have no merge request.

If I git pull -r with local commits I don't get a merge request.

 I think that is the key unless your doing something I am not understanding. I am not asking for PR into the interior-upgrades branch, maybe that is the difference?
or if

**Comment by onox** [comment]
@legoboyvdlp What you can do (in the future) is `git pull --rebase upstream some-branch`. Make sure you have a remote called `upstream` that has our repository as URL. After you have done the pull, you can push to `origin` (your fork on Github).

**Pull request closed without merging**
