### PR TITLE
Correct a segfault caused when you lower and then raise the amphibious gear on land

### LINKED ISSUE #1284: Segfault when lowering amphibious gear on land
Segfault is caused when you lower and then raise the amphibious gear on land.

### PR DESCRIPTION
**Pull request by wlbragg**
Fixes #1284

### CODE REVIEW

**Comment by gilbertohasnofb** [comment]
@wlbragg I still can't run FG but the code looks good and you certainly tested that the segfault is fixed with this. Given the urgency of the fix I am merging this. Should we bother Stuart once again for yet another cherry-pick + merge?

**Comment by wlbragg** [comment]
@gilbertohasnofb I pinged Stuart with this. If he gets it into the release we can then cherry pick it to our release branch. Thanks for getting it merged.

**Comment by dany93** [comment]
@wlbragg @gilbertohasnofb 

I have tested it, it works with no problem. Lowering and then raising the amphibious gear on land gave no fault.

For testing, I could reproduce the issue **in my previous git pull**, and It fixed it, 
In my previous git pull, I got:
```
In file /home/dany/FG/github/c172p/Systems/c172p-ground-effects.xml: line 1277
Malformed conditional check in function definition.
Fatal error (const char*): Fatal Error.
```
and the simulator was completely freezed.

**Comment by stuartbuchanan** [comment]
Hi Folks,

Please push this to your 2019.1 release branch so myself or James can merge it in.

Also, not sure if the commit to fix the warning messages was also merged into your branch - I merged the changes manually into fgdata.  If not, please push those also.

Thanks!

-Stuart

**Comment by wlbragg** [comment]
I won't be able to do this until later on this evening about 6 hours from now. I will take care of it then if no one beats me to it.

**Comment by wlbragg** [comment]
@stuartbuchanan this is ready.
https://github.com/c172p-team/c172p/commit/c4ca3ab7396a19ceeb5eea7f03b1c56a7a411de4

**Pull request merged**
