### PR TITLE
Issue 1344 (additions to original 1344 branch)

### PR DESCRIPTION
**Pull request by hbeni**
Additions from Saschas recent code, see https://github.com/c172p-team/c172p/issues/1302#issuecomment-870857727

### CODE REVIEW

**Comment by wlbragg** [comment]
@hbeni I can go through this one item at a time and update the KAP myself. I cannot use this as is the because of the material and effect changes.

But now I am concerned that these changes broke it? Is that true?

I'm referring to these comments https://github.com/c172p-team/c172p/issues/1302#issuecomment-870857727
Specifically...
>Probably related: without the commit, the device does not display the status on the left side anymore. Something broke. With the commit the all the lights on the autopilot do not work anymore.

I'm confused also why these changes are not in the c182s or being proposed for the c182s? If you answer this question in the other post, please ignore this one.

**Comment by hbeni** [comment]
> @hbeni I can use this "as is" once you tell me your done, I will cherry pick the appropriate parts now that I understand what is going on.

If Sasche doesn't bring up new stuff, I'm done.
I would say, we just wait a a bit and see if something comes up.
Tomorrow Sascha and I probably will talk a little after the Wednesday-GA event.

**Comment by wlbragg** [comment]
@hbeni 
Looking this over all I see that can't be merged right in is the 
KAP140: Effects changes
Can you back that out so I can just merge this as is?

**Comment by hbeni** [comment]
> Can you back that out so I can just merge this as is?

Pushed :D

**Comment by hbeni** [comment]
> > Can you back that out so I can just merge this as is?
> 
> Pushed :D

Oh dear, now the AP has the glass issue again. Did you forgot to push your fix?

**Comment by hbeni** [comment]
@wlbragg i need your help :D

**Comment by wlbragg** [comment]
@hbeni If your talking about the glass in the ac. This is pushing a new .ac or maybe your first ac? Not the one I pushed to #1344?
I can fix it again after this merge if needed, right?

**Comment by wlbragg** [comment]
KAP140: Update to model from Sascha is pushing another .ac, must be without my fix.

**Comment by wlbragg** [comment]
Didn't I see @reiszner say something about adding a glass to the model? That would need editing or removed from our branch as that is done in a customized way. The first time I merged your branch I had to adjust the glass as I guess the KAP140 face position must have changed slightly.

**Comment by wlbragg** [comment]
I'm not sure how your local flow goes, but if you merged this locally over the latest #1344 I think it would overwrite my changes to the glass, right?

**Comment by reiszner** [comment]
If you dont want the glass, you can insert a select-animation for it with a condition that will never become true.

**Comment by wlbragg** [comment]
I think the confusion may be you both are unaware of the fact that all the glass for every instrument is in the c172p.ac, not with the instruments themselves, including the KAP140. 
OK, I just manually merged this into a copy of my local and here is what happened.
The new ac glass is an issue but not to worry, I'll deal with it after I merge. I'll just delete it in our repository. As I said, our glass for that is custom. Some day I may use the individual glass with each instrument, but at the time I set up the glass effects it was easier to have them as one object.
But now the only other issue I noticed was that the buttons are no longer animated, was this always the case or is one of the param aliases messed up?

**Comment by reiszner** [comment]
Please 'grep' through the kap140.ac if it includes the object 'knob-axis'.
`grep knob-axis kap140.ac`
All animations are bound to this object.

**Comment by wlbragg** [comment]
>knob-axis

I know how to fix it manually, but I thought you set it up to be centered without positioning offsets?

> import the object 'glass' from kap140.ac into c172s and merge it to your instrument glass

Yes, I'll do that after the merge, good idea.

>For the glass in the kap140.ac, write a select animation thats always evaluate to false.

I create a local dev/blend of the .ac and I shut off the rendering on export back to an .ac so the glass doesn't exprot. No need for additional objects or code you don't need.

**Comment by reiszner** [comment]
Oh, you re-exported it.
Make sure to check the option 'Export lines'.
Otherwise the addon doesnt export axis objects.

**Comment by wlbragg** [comment]
>Otherwise the addon doesnt export axis objects

Oh, ok, I wondered how that system worked. I never used it. I hope I have the correct ac exporter. I think I do.

**Comment by reiszner** [comment]
Here is my KAP140 repo if you dont have the latest blend-file.
https://github.com/reiszner/KAP140

**Comment by wlbragg** [comment]
That was it, thank you!

**Pull request merged**
