### PR TITLE
Fg1000 variant

### LINKED ISSUE #1333: Create FG1000 panel variant
I hope there isn't already an issue for this. I couldn't figure out how to effectively search through the existing issues.

Because glass is now the future of aircraft, I think we need a glass variant. I did the PA-18 and it really wasn't that difficult to retrofit it. We could do the same thing with our flagship and probably should. I think it would have to be done the same way as I did the PA-18 and it would have to have it's own set file and that would be the only way to access it. Not on the fly like the gear and engine changes. It's too heavy and cause the other PA-18 variants to lag even when in the background.

What I think is needed most for this is just some good cockpit reference material the matches our c172p model as best we can find. This winter when I'm holed up maybe I can start on this with a little help here and there.

maxresdefault

### PR DESCRIPTION
**Pull request by wlbragg**
Fixes #1333 

DO NOT MERGE YET

### CODE REVIEW

**Comment by wlbragg** [comment]
@legoboyvdlp this is ready to thoroughly test.
This PR includes...
The compositor upgrade.
The new brake logic.
The new KAP140. We need to merge the KAP140 PR first once it it tested. This PR refactor that work considerably.
This PR includes two new FG1000 variants, GFC and KAP equipped.
It including a new electrical system for the FG1000 and a slightly upgraded electrical for the standard c172p.
This PR also includes a major refactoring of the variant sets. They are way better organized and eventually I want to add better previews and splash screens to fit the variants..

**Comment by wlbragg** [comment]
@legoboyvdlp this is to a point I think it is ready to merge. I really wish we had more people to test this thoroughly though. 
Here is my thoughts. The original variants should function the same as always. There was some refactoring of the sets but really nothing that major.
The fg1000 could be massaged and worked on to infinitum , but we don't have the bodies to nit pick like we used to have at the peak of most of the upgrading we have done to this aircraft. So I think it best to get this merged and out there to the masses, hopefully any issues will be exposed and trickle back to us that way. Otherwise it will sit here for another year, unused and work waisted.
So once again, if you could take it through its paces and test the basics of all the variants to make sure nothing major has been overlooked, we can get this merged.
@dany93 if you have any time to test, that would be appreciated as well.

**Comment by hbeni** [comment]
> DO NOT MERGE YET

Just a hint: you can convert the PR to „draft“ which makes it grey and unmergeable ;)

**Comment by wlbragg** [comment]
How?

**Comment by hbeni** [comment]
> @hbeni
> No take backs,ha! How do you make the PR a draft?

I had seen that you wrote that this PR is ready.

Here is the docs :) https://docs.github.com/en/github/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/changing-the-stage-of-a-pull-request#converting-a-pull-request-to-a-draft

**Comment by wlbragg** [comment]
@legoboyvdlp your welcome to test everything, but don't merge yet. I have a little more to do with the interior lighting. I'll remove the DO NOT MERGE YET when I am done and let you know here in another post. But all I am actively working on is the interior lighting effects. Specifically residual radiance.

**Comment by legoboyvdlp** [comment]
Just to check is it expected that the FG1000 comes online immediately when you turn the batteries on (its not the avionics switch)?

**Comment by legoboyvdlp** [comment]
The ADF animations seem to be broken too.

**Comment by legoboyvdlp** [comment]
Performance is also really quite bad for me; normally I'd see about 30 fps in the Cessna but its now down to about 5 or 6!

Small minor thing: the update rate of the engine instruments is extremely low; couldn't that be increased to make them smoother?

**Comment by wlbragg** [comment]
Yes, the left mfd comes on. The right requires avi 1 or 2 switch, if iremember correctly.

I'll check on the adf.

**Comment by legoboyvdlp** [comment]
I was using the KAP140 variant by the way when the ADF knob animation wasn't working.

Minor bug: the stby arm tooltip doesn't actually show a value.

As for the GFC700; I can't get the selected altitude or heading bug to change. A lot of errors in the console:
 Nasal runtime error: setprop() value is not string or number
  377.39 [ALRT]:nasal        at , line 3
  383.60 [ALRT]:nasal      Nasal runtime error: setprop() value is not string or number
  383.60 [ALRT]:nasal        at , line 3
  430.60 [ALRT]:cockpit    empty 'not' condition
  430.60 [ALRT]:cockpit    empty 'not' condition
  430.61 [ALRT]:cockpit    empty 'not' condition
  430.61 [ALRT]:cockpit    empty 'not' condition
  430.61 [ALRT]:cockpit    empty 'not' condition
  430.61 [ALRT]:cockpit    empty 'not' condition
  430.61 [ALRT]:cockpit    empty 'not' condition
  430.61 [ALRT]:cockpit    empty 'not' condition
  430.61 [ALRT]:cockpit    empty 'not' condition
  430.61 [ALRT]:cockpit    empty 'not' condition
  430.61 [ALRT]:cockpit    empty 'not' condition
  430.61 [ALRT]:cockpit    empty 'not' condition
  430.61 [ALRT]:cockpit    empty 'not' condition
  430.62 [ALRT]:cockpit    empty 'not' condition

**Comment by wlbragg** [comment]
OK thanks, I know it used to work. I'll will look into it.

**Comment by wlbragg** [comment]
@legoboyvdlp I think a pull with the new commits fixed your problem with the hdg bug. I  tied a <not> statement that was not legal in a filter or logic statement. I think it killed nasal.
Anyway I'm not seeing it anymore. I'm still struggling with the residual lighting effects. Getting close but it is a monster.  Nothing that should affect anything except levels of residual lighting in the cockpit.

**Comment by wlbragg** [comment]
OK, error should be gone but still working on residual.

**Comment by wlbragg** [comment]
Notes to myself:
procedural lights on 3 gauges
glass lighting reflection 
als and low spec residual lighting

**Comment by legoboyvdlp** [comment]
Thanks; will check it out :-)

It's really quite impressive what you have done - big step forward for the C172 once all the bugs are ironed out!

**Comment by wlbragg** [comment]
@legoboyvdlp thanks, I'm really happy with it. The one thing I really wish we could acquire is a new model for it.

We're getting closer to being able to merge this. I think the ALS residual is finished. Still a review of the electrical for the avionics and ow spec residual and windscreen glass glare/reflection.

**Comment by wlbragg** [comment]
@legoboyvdlp this is NOT READY to merge but it is ready to test the all the interior lighting, residual ambiance, glass glare, knobs and switch function.
Still to do on the lighting is to remove the red and white dome lighting and install a different type of twinwhite dome lights. They are supposed to be two individual small white directional lights. I decided to go ahead and make them.
I'm mostly done with the electrical, jut need to make sure a it's all set up to specs for the glass cockpit.

**Comment by wlbragg** [comment]
Dang it. I'm working with a new laptop and keep hitting some key combination that closes the PR.

**Comment by wlbragg** [comment]
@legoboyvdlp and everyone else watching this branch. I just pushed a massive refactoring of the lighting effects for both the c172p and the new FG1000 variant. There really was no way to do this piecemeal. It was too massive and  touched too many areas of the code to try to do it a little bit at a time.
As I was testing the existing fg1000 work I realized the "partial" integration of the fg1000 variant that was completed at the time wasn't going to cut it. It started when I decided to add a differ dome lighting system to the FG1000 variant. The glass c172 has a twin white dome lamp system and so we have one too now. But, during the creation of that system I realized there were many systems not integrated correctly. One thing lead to another and before I knew it I had a almost stand alone fg1000 model. In the long run though, this is a good thing because the c172p and the fg1000 are more separated than they were and now it will be way easier in the future to upgrade the fg1000 model without bothering or touching the c172p model or systems. There is still much overlap where the two aircraft are identical and the same systems can work for both of them but the lighting, electrical, interior panel systems and main model components are separated nicely. Part of this massive refactoring was to accommodate the livery system which was broken of the fg1000 side but now works fine. There is room for improvement in the fg1000 interior livery portion (ie: livery map needs to be created). But all the livery choices can still be used in the fg1000 variant.
I made the entire set of interior lightmaps for the fg1000 variant which required a complete lightmap blend created to accommodate the burning. So as far as I am concerned, the fg1000 lighting and effects are on par with the c172p but are completely new. Another reason for the need to separate the variants more completely was because of the interior implicit lighting of the panels. This required a completely different and stand alone effects scheme.
Something else I discovered as I got into this was that we had a bunch of unneeded effect files. These unneeded effect files were no longer needed now that the compositor scheme is in place. Actually I am not too sure they were ever really needed once i realized a couple different methods to burn lightmaps and how to more effectively use the effects framework.
Long, long story short. The difference between what was here before this last update and what is here now is day and night.
The thing is though, I need as many people as possible to start testing and using both the original c172p variants and the fg1000 variants. Really put them through their paces. Test day and night operations, all the equipment, and gear variations including hydo, rudder trim, elevator trim, fuel tank capacities and "realistic" fuel system procedures. Well, everything you can think of. This aircraft is so complex, there is just so much that needs to be tested. I have spent many, many, many man hours on this new variant and I am really happy with where it is at and the health of the integration. Even with that said, I can't envision there not being something I missed. So please help test and as soon as we decide it is sound, we can cut a new release and get it out there for some broader testing. I still want to review the fg1000 electrical and do some thorough testing myself before I am ready to merge. But it is at a state were anyone can help test the original variants (they should perform as they always have) and the new fg1000 variant is complete enough to test all aspects as well. I just have a final walkthrough I want to make myself, so to speak.

Oh, one thing I wanted to get an opinion on is we can use this branch as is and eventually merge it. Or, I made a new branch locally and cloned master then added the entire new fg1000 variant, all at once in one commit so it is less convoluted. Would it be better to merge that branch when the time comes than this more convoluted existing branch?

**Comment by hbeni** [comment]
> Oh, one thing I wanted to get an opinion on is we can use this branch as is and eventually merge it.

Good morning, I would say, stay with the project historys way of dealing with it.
OTOH, maybe one single commit is better in this case, because it could more easily be reverted if something catastrophic happens.
I did a quick flight with the FG1000 and the clock museum standard variants and all seemed well :)

**Comment by hbeni** [comment]
So, I played a little more with the standard variant and the FG1000; and I did not find something obvious.
I did just test basic flight, some lighting stuff (night/day), KAP140 autopilot, Takeoff, cruise, landing, and basic flight maneuvers.

**Comment by wlbragg** [comment]
@hbeni thank you for testing. I took a trip in the fg1000 variant today and tested the NAV/COM radios and the AP. Stuart did nice work on the fg1000. I'm trying to learn all the navigation tools available within its framework.

**Comment by legoboyvdlp** [comment]
One bug I found: the XPDR value is "XPDR n i l ON". When I try and set the code it works but it doesn't let me switch to ALT or STBY.

**Comment by legoboyvdlp** [comment]
... also the speed / altitude doesn't update at all? That's really weird. Can anyone reproduce that?

**Comment by legoboyvdlp** [comment]
Error: 

string index 3 out of bounds (size: 3)
  190.52 [INFO]:nasal      C:/Users/redpa/Documents/FlightGear/fg-from-scratch/FlightGearBuild/fgdata/Aircraft/Instruments-3d/FG1000/Nasal/MFDPages/PFDInstruments/PFDInstruments.nas
  190.52 [INFO]:nasal      956
  190.52 [INFO]:nasal      C:/Users/redpa/Documents/FlightGear/fg-from-scratch/FlightGearBuild/fgdata/Aircraft/Instruments-3d/FG1000/Nasal/MFDPages/PFDInstruments/PFDInstrumentsController.nas
  190.52 [INFO]:nasal      478
  190.52 [INFO]:nasal      C:/Users/redpa/Documents/FlightGear/fg-from-scratch/FlightGearBuild/fgdata/Aircraft/Instruments-3d/FG1000/Nasal/MFDPages/PFDInstruments/PFDInstrumentsController.nas
  190.52 [INFO]:nasal      540
  190.52 [INFO]:nasal      C:/Users/redpa/Documents/FlightGear/fg-from-scratch/FlightGearBuild/fgdata/Nasal/emesary.nas
  190.52 [INFO]:nasal      179
  190.52 [ALRT]:nasal      Recipient PFDInstrumentsController_PFD has been removed from transmitter (GlobalTransmitter) because of the above error

**Comment by wlbragg** [comment]
@legoboyvdlp 
Thanks for the report.
The fg1000 nasal errors may be because I inadvertently pushed the version where I am actually updating the EIS page with the stby battery amps and voltages, but the EIS.nas file in fgdata doesn't have my additions yet, I have them locally. I just asked @stuartbuchanan if he would make the needed changes on fgdata. But a nasal error there might cause a cascade with other nasal instruments such as speed / altitude or XPDR. Let me check my local and see if I overlooked something related to any of your bug.
Also, if you want to replace the following lines in fgdata\Aircraft\Instruments-3d\FG1000\Nasal\EIS\EIS-C182T.nas with the following to see if that clears any of it up.
~~~
  updateEngineData : func(engineData) {
    me.setTextElement("RPMDisplay", sprintf("%i", engineData.RPM));
    me.setTextElement("ManDisplay", sprintf("%.1f", engineData.Man));
    me.setTextElement("MBusVolts", sprintf("%.01f", engineData.MBusVolts));
    me.setTextElement("EBusVolts", sprintf("%.01f", engineData.EBusVolts)); # TODO: Include Emergency Bus
    me.setTextElement("MBattAmps", sprintf("%+.01f", engineData.MBattAmps));
    me.setTextElement("SBattAmps", sprintf("%+.01f", engineData.SBattAmps)); # TODO: Include Emergency Bus
~~~
Give me a couple hours as of my time right now, to push one more batch of cleanup stuff and then try it again when you get a chance.
I'm getting ready to push a change that completely removes the Garmin196 from both of the fg1000 variants. It is also causing a intermittent nasal error and really there us no need to include it in the fg1000 variant. It is heavy to start with and so is the fg1000 so I don't think we should include both. I'm just about finished with that change.

**Comment by wlbragg** [comment]
OK @legoboyvdlp 
I pushed some updates. The alt, speed must be a cascading nasal error as I have no issues with it. The XPDR issue may be the same thing. I am unfamiliar with its use and so don't know what to look for. I am able to physically switch the settings on it if that was a problem, I don't have that issue.
Make sure you change the fgdata / EIS-C182T.nas code and get a fresh pull of this fg1000 variant branch too, then test again. The EIS was changed in this last commit so you need that change and the manual change you need to make to fgdata.
Let me know if this fixes your issues. Mine is clear of nasal errors and everything appears to be working correctly, thanks.

**Comment by legoboyvdlp** [comment]
Oh; I think that's right - it's probably just the nasal error that stops it updating :) Thanks!

**Comment by legoboyvdlp** [comment]
Hm, no the specific error is in a different place. Although you're right that its a nasal error preventing it from working.

Specifically the problem is that obj._transponder_code in PFDInstrumentsController line 109 is nil -- which then propagates through the system.

That means that page.mfd.ConfigStore.get("TransponderVFRCode"); is returning nil for some reason.


If I add 
> "TransponderVFRCode": 1200,

to Nasal/ConfigStore.nas inside the configValues vector then it does work.

So I'm wondering why it works for you ... it just seems like an omission or some unpushed work?

**Comment by legoboyvdlp** [comment]
Another thing, can't we make the engine data (RPM etc) update more smoothly?

**Comment by legoboyvdlp** [comment]
New bug - I tried making a DTO and got this:

 non-objects have no members
 1115.68 [INFO]:nasal      C:/Users/redpa/Documents/FlightGear/fg-from-scratch/FlightGearBuild/fgdata/Aircraft/Instruments-3d/FG1000/Nasal/MFDPages/DirectTo/DirectToController.nas
 1115.69 [INFO]:nasal      369
 1115.69 [INFO]:nasal      C:/Users/redpa/Documents/FlightGear/fg-from-scratch/FlightGearBuild/fgdata/Aircraft/Instruments-3d/FG1000/Nasal/MFDPages/DirectTo/DirectToController.nas
 1115.69 [INFO]:nasal      272
 1115.69 [INFO]:nasal      C:/Users/redpa/Documents/FlightGear/fg-from-scratch/FlightGearBuild/fgdata/Aircraft/Instruments-3d/FG1000/Nasal//MFDPageController.nas
 1115.69 [INFO]:nasal      165
 1115.69 [INFO]:nasal      C:/Users/redpa/Documents/FlightGear/fg-from-scratch/FlightGearBuild/fgdata/Nasal/emesary.nas
 1115.69 [INFO]:nasal      179
 1115.69 [ALRT]:nasal      Recipient DirectToController_MFD has been removed from transmitter (GlobalTransmitter) because of the above error





Seems to me like the DTO function assumes that a destination has already been set ( var name = destination.id;) .... there should be some error checking there to make sure that it guards against this when no destination has been set. I think that's a bug for @stuartbuchanan

**Comment by wlbragg** [comment]
>I think that's a bug for @stuartbuchanan

Yes, anything MFD or PFD is most likely for @stuartbuchanan
It may not be created yet? Explain the procedure to me and I can try it and see if mine is operational.

>can't we make the engine data (RPM etc) update more smoothly

I'm on a new i7 laptop with a really high end nVidia card so I am maybe not seeing the lag as bad as you are. But even with my system it does seem to jump VS transition when moving. That is @stuartbuchanan end as well. Wee need to pass this stuff along to him.

It just dawned on me that you were talking about the XPDR on the fg1000. I never tested that function. I tested the non fg1000 variant because I made considerable refactoring changes to that side and thought maybe I messed something up. So I tested it on the MFD/PFD just now and had no issues on it either.

Something tells me somehow you have a configuration error or maybe are missing something? How hard would it be for you to clear your aircraft cache c172p-fg1000-gfc.xml, and pull a fresh fg10000 variant branch?

Mainly because I don't have any answers for why that wouldn't be working by default and it is working on mine. Maybe @stuartbuchanan can answer why it is broken. It's enough to hang us up though if we can't sort it out.

**Comment by legoboyvdlp** [comment]
Yes, that worked to remove the transponder error. Thank you!



The other bug with the direct to is just a bug in developing the FG1000 so its still there.

**Comment by wlbragg** [comment]
Great, thank you so much for doing that and clearing this up. That could easily have been something Issed up as the last big commit was, well, big! So thank you.
I will be pushing one small update to the EIS tonight that adds CHT monitoring to the EIS.

**Comment by wlbragg** [comment]
@legoboyvdlp I have a shadow I can't account for, any idea where it's coming from?

sdwo

**Comment by stuartbuchanan** [comment]
Hi Folks

I’m away from my computer for the next week but will look at this in my
return.

Stuart

**Comment by legoboyvdlp** [comment]
Unfortunately I can't find it or think of any place it could come from :(

**Comment by wlbragg** [comment]
That's OK, Ill figure it out eventually.

**Comment by wkitty42** [comment]
> @legoboyvdlp I have a shadow I can't account for, any idea where it's coming from?

FWIW: that's an awful looking shadow...

i'm guessing that you have the sun-atlas-size fairly small in your setup? that's a compositor option in /sim/rendering/shadows...

FWIW2: AFAIUI, the c172p should not have any coded shadows any more since compositor takes care of the shadows automatically without anything needed for them in the craft code...

**Comment by wlbragg** [comment]
Nice guess @wkitty42 you made me look, ha, unfortunately that isn't it. I did have that line in the settings, but removed it long ago.

**Comment by wlbragg** [comment]
I found the shadow and fixed it. In the future a good clue as to what it is, if you can't find it easily, it is probably a procedural light. They leave shadows if not named and then excluded from the shadow bin. It was procedural courtesy lights.

**Comment by wlbragg** [comment]
@legoboyvdlp I'm waiting on @stuartbuchanan to add the stpy battery to the fg1000 EIS in fgdata, once that is done I'd ask you to merge this PR into master and I or you can walk through tagging a new version (2020.4). Then we can ask @stuartbuchanan to update fgdata next with that version and hopefully get some serious testing. So that is where I'm at right now. I just wanted to let you know what I am waiting for.

**Comment by legoboyvdlp** [comment]
OK! It's been pushed to FGData.

**Comment by legoboyvdlp** [comment]
No such member: setColor
  160.34 [INFO]:nasal      C:/Users/redpa/Documents/FlightGear/fg-from-scratch/FlightGearBuild/fgdata/Aircraft/Instruments-3d/FG1000/Nasal/MFDPages/Surround/Surround.nas
  160.34 [INFO]:nasal      251
  160.34 [INFO]:nasal      C:/Users/redpa/Documents/FlightGear/fg-from-scratch/FlightGearBuild/fgdata/Aircraft/Instruments-3d/FG1000/Nasal/MFDPages/Surround/SurroundController.nas
  160.34 [INFO]:nasal      106
  160.34 [INFO]:nasal      C:/Users/redpa/Documents/FlightGear/fg-from-scratch/FlightGearBuild/fgdata/Aircraft/Instruments-3d/FG1000/Nasal/MFDPages/Surround/SurroundController.nas
  160.34 [INFO]:nasal      499
  160.34 [INFO]:nasal      C:/Users/redpa/Documents/FlightGear/fg-from-scratch/FlightGearBuild/fgdata/Nasal/emesary.nas
  160.34 [INFO]:nasal      179



Hm, this is the new code added by Stuart.  I'll pass this on on the list.

**Comment by stuartbuchanan** [comment]
No need - I'll get it sorted shortly.  Didn't commit a change.

-Stuart

**Comment by legoboyvdlp** [comment]
Just one minor bug -- the stby battery tooltip doesn't actually show the position of the standby battery: it only always shows "STBY BATT: "

Once that is fixed I am happy to merge it!

**Comment by wlbragg** [comment]
OK, we're good to go!

**Pull request merged**
