### PR TITLE
Annunciator panel is only used in a KAP140 equipped aircraft

### LINKED ISSUE #1406: Annunciator panel is only used in a KAP140 equipped aircraft
The annunciator nasal code in annunciator_panel.nas was causing an error in the GFC version of the FG1000. Only aircraft equipped with the KAP140 should include this file. This issue moves the nasal loading of that file to only KAP140 equipped aircraft.

### PR DESCRIPTION
**Pull request by wlbragg**
Fixes #1406

### CODE REVIEW

**Comment by wlbragg** [comment]
@dany93 This is a minor bug fix.

Test to see that the KAP140 still works in all variants including the FG1000 KAP140 variant.
Before pulling if you run the FG1000 GFC variant, you should see a nasal error concerning the "annunciator" in the log. After this correction the error should be gone.

**Comment by dany93** [comment]
@wlbragg 

Confirmed. 
FG1000 GFC700, 
before pulling:
```
   74.31 [INFO]:nasal      Annunciator panel: initialized
   74.31 [ALRT]:nasal      Nasal runtime error: setprop() value is not string or number
   74.31 [ALRT]:nasal        at /home/dany/FG/github/c172p/Nasal/annunciator_panel.nas, line 212
   74.31 [ALRT]:nasal        called from: /home/dany/fgfs-A/install/flightgear/fgdata/Nasal/globals.nas, line 137
```
After pulling: No `Nasal/annunciator_panel.nas` error.

Tests:
With FG1000, I cannot do FG1000 tests because I have 2 to 8 fps, with graphics not complete. Crappy. Moreover, the rare figures I see are very small. My hardware (graphics card most probably) is insufficient.

However, I more or less could fly and test the KAP140 with FG1000 + KAP 140, the Default aircraft (160 hp), the Amphibious (180 hp) : the KAP140 works.

Are these test sufficient to say that I can merge?

**Comment by wlbragg** [comment]
>Something I don't understand: where is this annunciator? What is its connection with the KAP140?

It's the KAP140 panel, the one that beeps when it starts up and you see all the different functions for a second when it inits. Then it goes to BAR mode for adjustment.

It took me awhile to figure it out myself, The file name was c182p-annunciator.xml. I almost thought it got in there accidentally, then remembered the new KAP went into the c182 first and realized it came over with the new KAP140.

Yes, I am confident in this minor change. You can merge.

**Comment by wlbragg** [comment]
@dany93 Thank you!

**Pull request merged**
