### PR TITLE
Extended setup of startup state system

### PR DESCRIPTION
**Pull request by wlbragg**
Fixes issue #789 
See also #932 

Not ready to merge yet.

I started this for anyone that wants to work on it, test states as we create them and for any feedback or ideas.

We will need a state manager.
Also c172p.nas autostart and save switch settings will be affected and/or accounted for.

Some issues I foresee...
Autostart currently overrides state overlay settings.
Save switch states potentially overrides state overlay settings.

:warning: :warning: :warning:
 DO NOT MERGE UNTIL FURTHER NOTICE!
:warning: :warning: :warning:

### CODE REVIEW

**Comment by gilbertohasnofb** [comment]
@wlbragg do you plan to work on this for this release?

**Comment by wlbragg** [comment]
@gilbertohasnofb @onox I spent some time reviewing the state system they set up in the c182s and I think it was very well set up. It is pretty much a requirement to do it the way they did because of the complexities of our systems such as autostart and the saved switch state we already implement.
Basically I wanted to give you a heads up of my plans for this before investing a ton of time in it. I should fit nicely with our current systems. I think once I actually get into it I can have something to review in a couple days.

**Comment by gilbertohasnofb** [comment]
@onox do you think you could take care of reviewing this one? I don't have much knowledge about this and I am super busy before a long trip, so I am just trying to finish what is already on my plate before I travel on Monday :cry:

**Comment by gilbertohasnofb** [comment]
> I'm gonna miss you dude!

Me too, man! But I hope I will still be able to come around once in a while and check stuff in the repo while I am there, perhaps even test and merge stuff. It's been four years since I last went 'home' so my family will be understandably taking most if not all of my time. It's a pity it collides with this super busy pre-release period. So basically don't count on me but I might still be able to get something done in the evenings. Let's see :smile:

**Comment by wlbragg** [comment]
@gilbertohasnofb   @onox 
I had to revert the last commit I made here as I totally misread something and made a major change that didn't need changed. So please make sure you delete this branch and pull a fresh one the next time you want to work with it.

**Comment by gilbertohasnofb** [comment]
@onox do you think you can take a look at these two PRs concerning startup states and startup variants? I don't think I will have the time to take a proper look at this

**Comment by wlbragg** [comment]
@gilbertohasnofb @onox there is really nothing to look at on this PR yet. I'm still testing things, looking at what does and doesn't work, what we need and don't need.

**Comment by wlbragg** [comment]
:warning: :warning: :warning:
 DO NOT MERGE UNTIL FURTHER NOTICE!
:warning: :warning: :warning:

**Pull request closed without merging**
