### PR TITLE
FDM, pitching moment at zero alpha

### LINKED ISSUE #1232: FDM, pitching moment at zero alpha
FDM, change in cmo: pitching moment at zero alpha.
Alpha dependence of the pitching moment factor = cmo + (cm x alpha).

- Currently, cmo = 0.1 (constant).

_(With no flaps)_ 
It gives a climbing airspeed of 70 to 80 kt with no action on the yoke and no elevator trim correction after takeoff, when the airspeed increases (with pitch up and down oscillations). My impression is that the pitch up tendency is slightly too high.
Cruise (2400 RPM, 110 - 115 kt) necessitates an elevator trim correction of about about 0.2 to stabilize.

- This change:
cmo depends on qbar-psf (the dynamic pressure, depending on airspeed) as per [Megginson's tables](http://www.megginson.com/Aviation/roskam-coefficients.html#sec.data).

With this change, one needs to slightly pull the yoke to rotate and takeoff. After that, the aircraft climbs at about 85 to 95 kt kt with no action on the yoke and no elevator trim correction. Climbing at 80 kt is obtained by slightly pulling the yoke. Loosening the yoke gives an acceleration. More reassuring and, I think, closer to a real behavior (although this behavior is a choice which can be made by the elevator trim at takeoff).
For cruising (about 110 kt straight and level flight) an elevator trim correction of a bit less than 0.1 is enough.

### PR DESCRIPTION
**Pull request by dany93**
Fixes #1232

### CODE REVIEW

**Comment by legoboyvdlp** [comment]
is this mergeable?

**Comment by legoboyvdlp** [comment]
I can tonight.

**Comment by dany93** [comment]
Thank you.

**Comment by legoboyvdlp** [comment]
I didn't notice anything massively wrong although I obviously don't have any actual flight experience to comment on it. Everything looks fine.

I think its fine to merge it.

**Comment by dany93** [comment]
Thank you for your cooperation.

**Comment by legoboyvdlp** [comment]
I'll merge this later if there are no objections?

**Comment by dany93** [comment]
Thank you, lego.

**Pull request merged**
