### PR TITLE
Material animation and effects definitions come after knob animations

### LINKED ISSUE #1410: Material animation and effects definitions load order must come after knob animations
See https://github.com/c172p-team/c172p/issues/1210#issuecomment-1402789278

Requires rearranging the affected object knob animations to be loaded prior to any affect or material animation.

>[amalon](https://github.com/amalon) commented [5 days ago](https://github.com/c172p-team/c172p/issues/1210#issuecomment-1402789278) • 
This appears to be a simgear bug, being discussed on the flightgear-devel mailing list ("SGPickAnimation applying multiple times in the presence of SGMaterialAnimation"), where animations are applied multiple times to objects which appear multiple times in the scene graph, which happens after an effect node.

>It can be worked around by putting the animation node after the effect node in the XML (and putting the factors/ranges back to correct values). I'm in the process of adding a warning to simgear for when an animation is applied multiple times, to encourage it to be worked around (with a view to possibly fixing the behavior in the future), and to spot new cases.

>I'd appreciate feedback on how practical this sort of workaround is in the case of the c172p. It seems that animation nodes in c172-common.xml would have to go before effect nodes in Interior/Panel/c172p-panel/c172p.xml, so it'd presumably require some rearranging. If this is a giant pain, would you prefer a flag somewhere (perhaps at an XML file level, or individual animation node level) to allow you to explicitly state that you want the corrected behaviour (and to silence the warning), at the cost of losing compatibility with versions of flightgear prior to the introduction of the flag?

>This is the output of my current warnings for c172p (not yet pushed into simgear):

>    4.59 [ALRT]:general    Deprecation Alert: Since 2013, knob & slider animations are duplicated if they already take part in an effect,
    4.59 [ALRT]:general        resulting in exaggerated motion. This incorrect behaviour will be removed in a future version, which will reduce
    4.59 [ALRT]:general        the motion of these objects. Aircraft can work around the issue and silence this warning by rearranging the XML
    4.59 [ALRT]:general        so that the animation node comes before the effect node. You may need to double the animation factor or
    4.59 [ALRT]:general        property-adjust ranges to match the current range of motion. The affected object names will be logged below.
    4.59 [ALRT]:general    Warning: Duplication of knob animation on object "AdjustKnob" is deprecated behaviour (see above).
    4.66 [ALRT]:general    Warning: Duplication of knob animation on object "disk" is deprecated behaviour (see above).
    4.77 [ALRT]:general    Warning: Duplication of knob animation on object "Volume" is deprecated behaviour (see above).
    4.77 [ALRT]:general    Warning: Duplication of knob animation on object "FRQInner" is deprecated behaviour (see above).
    4.77 [ALRT]:general    Warning: Duplication of knob animation on object "FRQOuter" is deprecated behaviour (see above).
    5.80 [ALRT]:general    Warning: Duplication of knob animation on object "toggle-stbybatt" is deprecated behaviour (see above).
    5.80 [ALRT]:general    Warning: Duplication of knob animation on object "knob-swcb" is deprecated behaviour (see above).
    5.80 [ALRT]:general    Warning: Duplication of knob animation on object "knob-stbyind" is deprecated behaviour (see above).
    5.80 [ALRT]:general    Warning: Duplication of knob animation on object "knob-pedestal" is deprecated behaviour (see above).
    5.80 [ALRT]:general    Warning: Duplication of knob animation on object "knob-avionics" is deprecated behaviour (see above).
    5.80 [ALRT]:general    Warning: Duplication of knob animation on object "TrimWheel-fg1000" is deprecated behaviour (see above).
    5.80 [ALRT]:general    Warning: Duplication of knob animation on object "RudderTrimKnob-fg1000" is deprecated behaviour (see above).
    6.22 [ALRT]:general    Warning: Duplication of knob animation on object "AdjustKnob" is deprecated behaviour (see above).
    6.24 [ALRT]:general    Warning: Duplication of knob animation on object "disk" is deprecated behaviour (see above).
    6.48 [ALRT]:general    Warning: Duplication of knob animation on object "Hdg-Knob" is deprecated behaviour (see above).
    6.48 [ALRT]:general    Warning: Duplication of knob animation on object "OBS-Knob" is deprecated behaviour (see above).
    6.55 [ALRT]:general    Warning: Duplication of knob animation on object "disk" is deprecated behaviour (see above).
    6.61 [ALRT]:general    Warning: Duplication of knob animation on object "disk" is deprecated behaviour (see above).
    6.65 [ALRT]:general    Warning: Duplication of knob animation on object "HDGSelector" is deprecated behaviour (see above).
    6.68 [ALRT]:general    Warning: Duplication of knob animation on object "COMvol" is deprecated behaviour (see above).
    6.68 [ALRT]:general    Warning: Duplication of knob animation on object "COMknobKHZ" is deprecated behaviour (see above).
    6.68 [ALRT]:general    Warning: Duplication of knob animation on object "COMknobMHZ" is deprecated behaviour (see above).
    6.68 [ALRT]:general    Warning: Duplication of knob animation on object "NAVvol" is deprecated behaviour (see above).
    6.68 [ALRT]:general    Warning: Duplication of knob animation on object "NAVknobKHZ" is deprecated behaviour (see above).
    6.68 [ALRT]:general    Warning: Duplication of knob animation on object "NAVknobMHZ" is deprecated behaviour (see above).
    6.70 [ALRT]:general    Warning: Duplication of knob animation on object "COMvol" is deprecated behaviour (see above).
    6.70 [ALRT]:general    Warning: Duplication of knob animation on object "COMknobKHZ" is deprecated behaviour (see above).
    6.70 [ALRT]:general    Warning: Duplication of knob animation on object "COMknobMHZ" is deprecated behaviour (see above).
    6.70 [ALRT]:general    Warning: Duplication of knob animation on object "NAVvol" is deprecated behaviour (see above).
    6.70 [ALRT]:general    Warning: Duplication of knob animation on object "NAVknobKHZ" is deprecated behaviour (see above).
    6.70 [ALRT]:general    Warning: Duplication of knob animation on object "NAVknobMHZ" is deprecated behaviour (see above).
    6.73 [ALRT]:general    Warning: Duplication of knob animation on object "AUTO" is deprecated behaviour (see above).
    6.73 [ALRT]:general    Warning: Duplication of knob animation on object "COM1" is deprecated behaviour (see above).
    6.73 [ALRT]:general    Warning: Duplication of knob animation on object "COM2" is deprecated behaviour (see above).
    6.73 [ALRT]:general    Warning: Duplication of knob animation on object "NAV1" is deprecated behaviour (see above).
    6.73 [ALRT]:general    Warning: Duplication of knob animation on object "NAV2" is deprecated behaviour (see above).
    6.73 [ALRT]:general    Warning: Duplication of knob animation on object "ADF" is deprecated behaviour (see above).
    6.73 [ALRT]:general    Warning: Duplication of knob animation on object "DME" is deprecated behaviour (see above).
    6.73 [ALRT]:general    Warning: Duplication of knob animation on object "MKR" is deprecated behaviour (see above).
    6.73 [ALRT]:general    Warning: Duplication of knob animation on object "SENS" is deprecated behaviour (see above).
    6.73 [ALRT]:general    Warning: Duplication of knob animation on object "Knob" is deprecated behaviour (see above).
    6.74 [ALRT]:general    Warning: Duplication of knob animation on object "Volume" is deprecated behaviour (see above).
    6.74 [ALRT]:general    Warning: Duplication of knob animation on object "FRQInner" is deprecated behaviour (see above).
    6.74 [ALRT]:general    Warning: Duplication of knob animation on object "FRQOuter" is deprecated behaviour (see above).
    7.26 [ALRT]:general    Warning: Duplication of knob animation on object "TrimWheel" is deprecated behaviour (see above).
    7.26 [ALRT]:general    Warning: Duplication of knob animation on object "RudderTrimKnob" is deprecated behaviour (see above).
    7.26 [ALRT]:general    Warning: Duplication of knob animation on object "panel-light-knob" is deprecated behaviour (see above).
    7.26 [ALRT]:general    Warning: Duplication of knob animation on object "radio-light-knob" is deprecated behaviour (see above).
    8.35 [ALRT]:general    Warning: Duplication of knob animation on object "visorleft-fg1000" is deprecated behaviour (see above).
    8.35 [ALRT]:general    Warning: Duplication of knob animation on object "visorleft" is deprecated behaviour (see above).
    8.35 [ALRT]:general    Warning: Duplication of knob animation on object "visorright-fg1000" is deprecated behaviour (see above).
    8.35 [ALRT]:general    Warning: Duplication of knob animation on object "visorright" is deprecated behaviour (see above).
    8.35 [ALRT]:general    Warning: Duplication of knob animation on object "visorrodleft-fg1000" is deprecated behaviour (see above).
    8.35 [ALRT]:general    Warning: Duplication of knob animation on object "visorleft-fg1000" is deprecated behaviour (see above).
    8.35 [ALRT]:general    Warning: Duplication of knob animation on object "visorrodleft" is deprecated behaviour (see above).
    8.35 [ALRT]:general    Warning: Duplication of knob animation on object "visorleft" is deprecated behaviour (see above).
    8.35 [ALRT]:general    Warning: Duplication of knob animation on object "visorrodright-fg1000" is deprecated behaviour (see above).
    8.35 [ALRT]:general    Warning: Duplication of knob animation on object "visorright-fg1000" is deprecated behaviour (see above).
    8.35 [ALRT]:general    Warning: Duplication of knob animation on object "visorrodright" is deprecated behaviour (see above).
    8.35 [ALRT]:general    Warning: Duplication of knob animation on object "visorright" is deprecated behaviour (see above).

### PR DESCRIPTION
**Pull request by wlbragg**
Fixes #1410

### CODE REVIEW

**Comment by wlbragg** [comment]
@dany93 what do you think about going ahead and merging this issue and I will create another issue to modify the saved data and remove the unneeded transponder data. 

One question though, even if we fix the transponder cache data issue, you still would have an error until the second time you load the aircraft? Or can you tell me how this works. If you delete the saving of the two problematic properties, as if you just downloaded the new version, then run it, you get the error, right? But then if you exit normally and restart, all is well?

**Comment by dany93** [comment]
>One question though, even if we fix the transponder cache data issue, you still would have an error until the second time you load the aircraft?....

Sorry, I'm afraid of understanding almost nothing.

In avionics.nas, if  I delete or comment out these two lines like this
```
aircraft.data.add(
#    "instrumentation/transponder/inputs/knob-mode",
#    "instrumentation/transponder/inputs/ident-btn",
```
and start with no `aircraft-data/c172p-fg1000-kap.xml` cache or a cleaned one (once!), it works permanently with no extra intervention.

Which means that if you merge an avionics.nas file like this in master, it will work. It will be the new version and even if I reload it, it will work.

The cache `aircraft-data/c172p-fg1000-kap.xml` will be like this:
```
    <transponder>
      <inputs>
        <digit type="int">0</digit>
        <digit n="1" type="int">0</digit>
        <digit n="2" type="int">2</digit>
        <digit n="3" type="int">1</digit>
      </inputs>
    </transponder>
```
Clean. Ready for the next time without having to delete the two lines.

The case when I have to clean the cache each time is when the lines are in avionics.nas.

Obviously, if you merge the fixed avionics.nas and I start without cleaning the cache, I have the error. But it is not an issue, deleting the cache **once** is enough, permanently.

**Comment by dany93** [comment]
> and remove the unneeded transponder data.

I'm worried: do these transponder data are really unneeded? Or do they have to be replaced for data which are fitted to the FG1000?

**Comment by wlbragg** [comment]
>Which means that if you merge an avionics.nas file like this in master, it will work. It will be the new version and even if I reload it, it will work.

Ok, I think your right. You will be starting the aircraft that will load the "OLD" saved data cache and it will create those two properties. But then, because there is no longer a command to save them on the next exit, any subsequent loading wont have those two properties saved and thus they will be gone from that point on.
I actually thought about checking for those properties in the new version and if they are there (because they loaded automatically) have a message popup stating the issue and error you might have and simply exit and restart to correct.

**Pull request merged**
