### PR TITLE
Mesh cleanup

### PR DESCRIPTION
**Pull request by legoboyvdlp**
This cleans up the mesh around the doors and baggage door... screenshots to follow!
I'm not really confident enough to tackle the air vent mesh issues: I think I reduced them but they are still present.

:warning: Do not merge :warning:

### CODE REVIEW

**Comment by legoboyvdlp** [comment]
image

image

image

image

**Comment by legoboyvdlp** [comment]
I'm afraid the uv-map may be slightly distorted on the bit between the rear windows and wings 😞

**Comment by gilbertohasnofb** [comment]
> I'm afraid the uv-map may be slightly distorted on the bit between the rear windows and wings

Can you post pictures of the distortion, please? Do try most liveries when you make these modifications (particularly the HD ones)

**Comment by legoboyvdlp** [comment]
Certainly: I will do this in the morning.

**Comment by gilbertohasnofb** [comment]
No rush, lego!

**Comment by wlbragg** [comment]
@legoboyvdlp why changes to the two blends?
I get dev/blender/c172p-mesh-rework.blend is your modifications?
Why is dev/blender/c172p.blend changed? Did you do something in it as well?
Also can you indicate exactly what mesh you worked in in a picture. I think I know but would like to be sure.

**Comment by legoboyvdlp** [comment]
Sure.

The mesh-rework blend I accidentally commited but removed. It was a renamed copy of c172.blend for backup purposes.

As for the areas, I'll show it in a picture but off the top of my head it was all doors including the baggage door, area around them, the windows, and a little improvement to the cowling.

**Comment by wlbragg** [comment]
@legoboyvdlp I see this is just the blend and not the .ac.
Never mind the pictures, don't take the time. I'll just compare the mesh and export my own .ac to compare in the sim.
Thanks

**Comment by wlbragg** [comment]
@legoboyvdlp looks really good. I haven't seen it in the sim yet but you can certainly see the improvement in the mesh.

jqm2ybi

afhqk9t

djiq0vr

**Comment by wlbragg** [comment]
@legoboyvdlp here are all the liveries affected.If you look at the first two it shows that the main issue is at the bottom left of the door.. The rest of it looks good. Obviously, part of the mesh correction includes remapping the textures. That is something I had to do with all the wing work and it was a real bear.
liv

**Comment by legoboyvdlp** [comment]
Thanks!
 
I've not tried uvmapping very much before I'm afraid, but I'll have a go and see how we get on.

I did do the main cabin door as well - is it ok?

**Comment by gilbertohasnofb** [comment]
This is looking really good, lego. 

> Obviously, part of the mesh correction includes remapping the textures. That is something I had to do with all the wing work and it was a real bear.

Yeah, these issues simply cannot be fixed from the texture themselves, it has to be done only through UV-mapping and modelling. But I think this should not be too difficult regarding the baggage door, right? Some liveries show quite clearly where it is now misaligned and distorted.

**Comment by wlbragg** [comment]
>I did do the main cabin door as well - is it ok?

I didn't notice any issue but wasn't looking closely at that. I'll take another look at it.

>I've not tried uvmapping very much before I'm afraid, but I'll have a go and see how we get on.

Because the door is an independent piece of mesh, it should be pretty easy. When the fuselage needs remapping then you get into a whole big can of worms. Same for the wings. Going across many objects complicates the whole process. Only being concerned with the baggage door should minimize the effort.

**Comment by legoboyvdlp** [comment]
I'm going out to my 'local' bank (which is not very local!) so I won't be around for most of the morning to deal with this. Sorry for the delay!

**Comment by wlbragg** [comment]
No rush, it's not going anywhere.  :laughing:

**Comment by legoboyvdlp** [comment]
This is the best I can do with the baggage door. I'll try and improve the fuselage a little without affecting liveries.

**Comment by gilbertohasnofb** [comment]
The baggage door is looking pretty good I think! @wlbragg what is your opinion?

**Comment by legoboyvdlp** [comment]
Unfortunately most of the liveries are still broken.

**Comment by wlbragg** [comment]
@legoboyvdlp you will discover that you can't edit portions of the mesh or uv map to clean up one livery, otherwise others will suffer. You almost have to do the entire object in question as a whole and try to remap it in the same manner as the original was. Then if it fits one livery it should fit the others. In the case of the baggage door, when I said it was the lower left portion that is messed up, ones first thought is to adjust that portion of the of map, but then that messes up every other part of the uv map that was correct to start with. So the solution is to start over and take the entire door and uv map it from the correct angle that it was originally uv mapped from. That is the trick part, figuring out exactly how that was mapped from the beginning. Sometimes I would have to go back in history to see the original mapping and then try to recreate it.
I spent hours on the wings and fuselage mapping to get it right after editing the cowling and wing mesh. After awhile you get the hang of it and it becomes a bit easier, that is until you run into a mapping that you can't figure out how it was originally mapped that way.

**Comment by legoboyvdlp** [comment]
It really is beyond my skill level I'm afraid. Sorry :disappointed:

But if this person on the FlightGear's forums can redo the entire model then it shouldn't even be necessary to do this anyway...?

**Comment by gilbertohasnofb** [comment]
Who is this person talking about redoing the whole model?

**Comment by wlbragg** [comment]
@legoboyvdlp let me take another look at the mesh and see if I can "easily" clean up the uv map. It shouldn't be too difficult and I don't want to loose your work as it really is nicely done.

@gilbertohasnofb the user is IceBreaker and there was a commitment on the table to redo or at least edit the J3Cub mesh. I asked if he would be interested in retopologizing the c172p.
Don't know the answer yet but maybe he will be interested.

**Comment by gilbertohasnofb** [comment]
All right, if he wants to join our team he would be totally welcome, particularly if he's a capable modeller. I can make him a contributor here if he wants to, just let me know.

**Comment by wlbragg** [comment]
OK, not too hard, I think. I think this is done? @gilbertohasnofb @legoboyvdlp please check all the liveries, I checked enough of them I was confident they all should be OK?
@legoboyvdlp note, I used the c172p,blend and not the c172p-mesh-rework.blend. I could tell the door was the new work and I finished remapping the texture and saved it before I realized I was working on the default blend and not the c172p-mesh-rework.blend. I hope all your edits made it into the default blend (c172p.blend).

**Comment by wlbragg** [comment]
Hum, I just noticed that the seats have the old seat frames under them, what's up with that? I don't want to accidentally overwrite the new seat frame mesh.

**Comment by wlbragg** [comment]
This sucks, we have to remember to always work on the same mesh, we can't have mesh being worked on in two different PR's. Part of it is my fault for having a mesh project sitting around for so long without being merged.

**Comment by gilbertohasnofb** [comment]
@wlbragg What is the other PR with mesh work?

**Comment by legoboyvdlp** [comment]
I renamed the c172p-mesh-rework.blend to c172p.blend (replacing the old one) so it should be fine.

That's a pity. If needed you can just ignore my changes -- I can easily redo them with the new.blend?

**Comment by wlbragg** [comment]
After we test the work in this PR, I can copy the fuselage and the door over to the work in the PR that have the seats, credit lego in that commit and we'll have the changes in the working mesh PR. So go ahead and please still double check the textures/liveries and let me know if they are all OK.

**Comment by legoboyvdlp** [comment]
image

image

image

Other than those three, they all look fine!

**Comment by gilbertohasnofb** [comment]
@wlbragg So besides what @legoboyvdlp pointed out, here are a couple more issues:

* there is a weird object appearing in all liveries. This is not due to texture, it's some new unwanted polygon I believe:

fg-0

* the point in which the back part of the wing and the fuselage meet seem to have some weird reflections, are those triangles in the mesh in the proper place?

fg-1

* this is a small detail, but ideally we want the normals of the baggage door to match the normals of the adjacent triangles of the mesh of the fuselage, so that the reflections match as seamlessly as possible. Notice in the image below how the horizon in the reflection does not match:

fg-2

* as lego pointed out, the only UV problem I see is in the left door in many liveries, here are two shots of two different ones but there are others. I suspect that fixing it for one of them will fix them all. 

fg-3
fg-4

**Comment by wlbragg** [comment]
Thanks guys for inspecting this closely. 
As far as the normals matching between the baggage door and the fuselage, I saw that but I am not sure how to fix it? Maybe @legoboyvdlp will have an idea how to fix it?
The rest of it I think I can clean up. The issue underneath does look like some duplicate mesh or something of the sort. I'll look at it and should be able to figure it out.

**Comment by legoboyvdlp** [comment]
unfortunately, I don't know how to fix that :(

**Comment by legoboyvdlp** [comment]
Is there anything I need to do?

**Comment by wlbragg** [comment]
I don't think so, I need to fix the one issue
>The issue underneath does look like some duplicate mesh or something of the sort. 

then I should just copy the changes to the adjustable seat PR (since that is the PR wwith existing mesh additions and edits). Once I do that we can tie this issue to that PR with the "Fixes XX" tag and when that PR is closed it will close this one.

**Comment by wlbragg** [comment]
OK, please check this.
I thin k the UV issues are corrected.
The duplicate mesh or whatever it is on the underside starboard side is not there in my version and thus should be gone in this branch.
The baggage door normals are cleaned up best I could.
Same with the port side under the wing, above the door. This one was due to the angle of the mesh right there. The normals point up VS to the side and thus were collecting more light. I split the mesh where it was hidden and was able to move the normal to point a little more to the side VS up. I really can't easily do any more. Check it all out and let me know if this is done. If it is I am going to append the mesh to the fog/frost PR and close this one.

**Comment by gilbertohasnofb** [comment]
Everything looks fine except for this bug here:

image

**Comment by wlbragg** [comment]
How do I fix something I am not seeing? :smile:
Can you give me anymore data on it. Is it every livery?
Does it mater time of day or location or angle?
Something to trigger this?

**Comment by gilbertohasnofb** [comment]
Every livery, any time of the day, any airport, any weather, only in this branch, only on the right-hand side of the fuselage. One more shot:

fgfs-screen-001

It does look to me to be an issue with the 3D model itself.

**Comment by wlbragg** [comment]
I agree, except I don't have the issue in my mesh.

http://i.imgur.com/xjGJ1nJ.png

http://i.imgur.com/etq7yAv.png

@gilbertohasnofb could you send me the blend and .ac in the branch that you have the trouble with?

**Comment by wlbragg** [comment]
Also notice the mesh in Blender doesn't even match the shape in your issue!

**Comment by legoboyvdlp** [comment]
I also cannot see it, although I do notice this - did I introduce this by accident?

image

image
image
image

**Comment by gilbertohasnofb** [comment]
@wlbragg here is the link for my files: https://www.dropbox.com/s/5023govo78lqejd/c172p-issue.zip?dl=0

That's a very weird bug, particularly since it is only present in this very branch here.

> I also cannot see it, although I do notice this - did I introduce this by accident?

@legoboyvdlp Could you be more clear, what is the issue in those circled areas? Looks normal to me.

**Comment by legoboyvdlp** [comment]
The top of the circle is a straight line - ie cut off.

**Comment by gilbertohasnofb** [comment]
That's intentional :smile:

**Comment by legoboyvdlp** [comment]
Ah ok!  😀

**Comment by wlbragg** [comment]
@gilbertohasnofb I used the .ac and checked the blend and there is nothing wrong that I can see. This is a real puzzler. How about I take the changes and append then to the fog and frost branch (I'll back up the originals in that branch just in case). Then you can switch to fog and frost branch, do a pull and we see if it goes away when added to the fog and frost branch?

**Comment by wlbragg** [comment]
@gilbertohasnofb pull the latest fog and frost branch and see if the bug is gone in that branch. If it is we can close out the 3dmesh PR as it is now included in the fog and frost PR.

@legoboyvdlp all I appended to the fog and frost branch from the 3dmesh branch was the fuselage and the baggagedoor objects. Is that all that had changes?

**Comment by legoboyvdlp** [comment]
The cowling also got some changes to reduce, not remove the shading issues as far as I know?

**Comment by gilbertohasnofb** [comment]
@wlbragg yep, the bug is also present there now, these are from the current fog and frost branch:

fgfs-screen-001
fgfs-screen-003

**Comment by gilbertohasnofb** [comment]
Could it be that there is a problematic vertex just under the centre of that grey blob? Maybe my GPU can't handle it while yours can ignore the issue. Just an idea. I can try to find what commit introduced it, would that be helpful? This way, if that commit is not too much in the past, we can then use the 3D model from that point.

**Comment by wlbragg** [comment]
Wow!

>I can try to find what commit introduced it, would that be helpful?

Yes.

**Comment by gilbertohasnofb** [comment]
@wlbragg ok, bad news, this was introduced by @legoboyvdlp in his very first commit of this branch, i.e. commit https://github.com/c172p-team/c172p/pull/1257/commits/01410dd9dcad646ae55fd7f69052d36379f073ea

**Comment by wlbragg** [comment]
@gilbertohasnofb can you pull this branch again and see if it works now. I simply remapped the step to see if that was the issue. I doubt it, but maybe we get lucky.

**Comment by gilbertohasnofb** [comment]
@wlbragg I am sure you meant the branch `glass-frost-and-fog-effect` and not this one. That branch is now broken for me after the last commit, the sim won't launch:

Screenshot from 2019-03-26 23-51-09

**Comment by wlbragg** [comment]
Yes, sorry!

**Comment by wlbragg** [comment]
@gilbertohasnofb  Oops, sorry about that as well, mistakenly forgot a property I needed to put back to original.

**Comment by gilbertohasnofb** [comment]
Good news, the model in the fog and frost branch has been fixed :tada:

**Comment by gilbertohasnofb** [comment]
we can close this PR then

**Comment by wlbragg** [comment]
Wow, we got lucky. Yes we can close this PR. It is all contained in the fog and frost PR.

**Comment by gilbertohasnofb** [comment]
Yes, we did get lucky, this would have been an nightmare to fix otherwise!

**Pull request closed without merging**
