### PR TITLE
Starting with battery and avionic-master on for tutorial

### LINKED ISSUE #1258: Radio tutorial has no power to radio upon startup
See:https://forum.flightgear.org/viewtopic.php?f=37&t=35246&p=342952#p341392

We need to add a section at the beginning of the tutorial on how to get power to the radio stack.

### PR DESCRIPTION
**Pull request by ltoenning**
Fixes #1258 

As this tutorial didn't take long time I guess just using battery is enough. Otherwise we may can also start the engine.

### CODE REVIEW

**Comment by gilbertohasnofb** [comment]
@ltoenning I think it's important to start the tutorial with the battery and avionics off and have the players switch them on. These tutorials are particularly important for new players, and this teaches them how the radio operates. So could you consider implementing that?

**Comment by ltoenning** [comment]
Sure. I just thought that normally the user would start with the first tutorials ("Preflight", "Engine Start" etc.) so they already knew how to power the aircraft up.

But I agree if someone just jumps into the "Radio Stack Tutorial" it might be confusing.

**Comment by gilbertohasnofb** [comment]
Great, many thanks! I think some users might do things out of order, others might take some time remembering things, so it might be nice to include this in this tutorial. Definitely not a super deal breaker, but nice nevertheless. Thanks for implementing it!

**Comment by ltoenning** [comment]
Ok will do tonight.

**Comment by ltoenning** [comment]
Update pushed.

**Comment by gilbertohasnofb** [comment]
@ltoenning Excellent work, thank you so much!

**Pull request merged**
