### PR TITLE
Issue 1167

### LINKED ISSUE #1170: Add sound for windows
Should the windows make some sound? Right now they are silent. I would imagine a kind of click as you move the lever and a squeak or something as you open the window?

### PR DESCRIPTION
**Pull request by gilbertohasnofb**
Fixes https://github.com/c172p-team/c172p/issues/1167
Fixes  #1170

### CODE REVIEW

**Comment by gilbertohasnofb** [comment]
@wlbragg this is ready for testing and being merged. I animated and added sound to the water rudder cable. Perhaps you might want to fix that UV-mapping issue I mentioned in our team discussion in this same PR.

**Comment by gilbertohasnofb** [comment]
please don't merge yet, I'm wokring on other sounds

**Comment by wlbragg** [comment]
@gilbertohasnofb Oops, sorry, I didn't see this, I fixed the mapping issue in the cowling PR.

**Comment by gilbertohasnofb** [comment]
No worries. I am almost done here, give me some minutes and we can merge this.

**Comment by gilbertohasnofb** [comment]
@wlbragg ready to be merged:

* new sounds for water lever and window latches
* better sound for flap lever click (not the flap motor)
* animated water lever cable

**Comment by wlbragg** [comment]
Perfect, I love the animation, sounds are great too!

**Pull request merged**
