### PR TITLE
Issue 1284

### LINKED ISSUE #1284: Segfault when lowering amphibious gear on land
Segfault is caused when you lower and then raise the amphibious gear on land.

### PR DESCRIPTION
**Pull request by wlbragg**
Fixes #1284 

This is a critical fix for Issue 1284. To test, prior to this fix, if you broke amphibious landing gear you would cause a simulator crash. This completely eliminates the issue as well as adding some ascetically pleasing gear control effect where the gear selector knob is functional but does nothing if the pontoon is broken. If damaged, it still works as it should. If broken, the gear is retracted as if the gear sensor is reading retracted and the water indicator lights are enabled and cannot be changed.

### CODE REVIEW

**Comment by wlbragg** [comment]
This is ready to go and should also be cherry picked to the current release if possible.

**Comment by gilbertohasnofb** [comment]
@wlbragg I am still having issues with my installation, I get a fatal error when I launch because we are using features that are not available in the last stable one (2018.3). @legoboyvdlp could you please test this and merge this? Otherwise, if you are confident that the fix is working you can also merge it yourself, @wlbragg, since this sounds very important.

**Comment by legoboyvdlp** [comment]
(There is a new release available by the way)

I'll be unable to test today at least, as I'm away painting a house, sorry.

**Comment by dany93** [comment]
I do not know what to test and how to test.

However, with FG 2019.2.0, OSG 3.4.2
```
cmake       8a42cd1 Tue, 2 Jul 2019 08:45:58 -0400
OSG         1f89e6e Sun, 3 Jun 2018 10:37:34 +0100
FlightGear  34a6cb3 Mon, 1 Jul 2019 14:51:32 +0200
SimGear     fa754ec Mon, 1 Jul 2019 14:37:49 +0200
FGData      2cd245a Sun, 30 Jun 2019 15:14:01 +0100
PLIB        a542b8a Wed, 4 Oct 2017 17:33:51 +0200

Linux Mint 18, Qt 5.5
```
C172P Issue-1284 f13009166a8 (2019-07-28)

The simulator starts with no crash.

These lines in the Console
```
Failed to tie property fcs/z-position-ground-factor-left-aft-pontoons to object methods
Failed to tie property fcs/z-position-ground-factor-right-aft-pontoon to object methods


   11.71 [ALRT]:input      Could not find 'Effects/schemes.xml'
   18.15 [ALRT]:input      Failed to load file: "Effects/interior/procedural_light_indicator_led_orange_large.xml"
   18.15 [ALRT]:input      Failed to load file: "Effects/interior/procedural_light_indicator_led_green.xml"
   18.15 [ALRT]:input      Failed to load file: "Effects/interior/procedural_light_indicator_led_green.xml"
   18.15 [ALRT]:input      Failed to load file: "Effects/interior/procedural_light_indicator_led_green.xml"
   18.15 [ALRT]:input      Failed to load file: "Effects/interior/procedural_light_indicator_led_green.xml"
   18.15 [ALRT]:input      Failed to load file: "Effects/interior/procedural_light_indicator_led_blue.xml"
   18.15 [ALRT]:input      Failed to load file: "Effects/interior/procedural_light_indicator_led_blue.xml"
   18.15 [ALRT]:input      Failed to load file: "Effects/interior/procedural_light_indicator_led_blue.xml"
   18.15 [ALRT]:input      Failed to load file: "Effects/interior/procedural_light_indicator_led_blue.xml"
   18.15 [ALRT]:input      Failed to load file: "Effects/interior/procedural_light_indicator_led_red.xml"
   30.27 [ALRT]:nasal      Volcanic activity on.
   30.41 [POPU]:nasal      ERROR: Cannot add listener to tied property /sim[0]/current-view[0]/view-number[0]
   30.47 [POPU]:nasal      ERROR: Cannot add listener to tied property /sim[0]/current-view[0]/view-number[0]
   30.47 [POPU]:nasal      ERROR: Cannot add listener to tied property /sim[0]/current-view[0]/view-number[0]
   30.78 [POPU]:nasal      ERROR: Cannot add listener to tied property /sim[0]/current-view[0]/heading-offset-deg[0]
   30.97 [ALRT]:nasal      KMA20 audio panel initialized
   30.99 [ALRT]:nasal      Hobbs system stopped
   30.99 [ALRT]:nasal      Hobbs system stopped
   30.99 [ALRT]:nasal      Starter off
   30.99 [ALRT]:nasal      Nasal parse error: parse error in /home/dany/FG/github/c172p/Nasal/avionics.nas, line 166
   31.04 [ALRT]:nasal      Electrical system initialized
   31.14 [POPU]:nasal      ERROR: Cannot add listener to tied property /instrumentation[0]/gps[0]/mode[0]
   31.15 [ALRT]:nasal      Astro Tech LC-2 Chronometer Loaded
   36.40 [ALRT]:nasal      Primer reset to 0
   52.51 [ALRT]:nasal      Cessna 172P Skyhawk (1982)
   52.51 [ALRT]:nasal      /home/dany/FG/github/c172p
   52.55 [POPU]:nasal      ERROR: Cannot add listener to tied property /sim[0]/current-view[0]/view-number[0]
   67.54 [ALRT]:nasal      Model load Nimitz /ai/models/carrier
   69.32 [ALRT]:nasal      Garmin 196 loading cities
   70.95 [ALRT]:nasal      Garmin 196 loading cities done
  125.60 [POPU]:nasal      ERROR: Cannot add listener to tied property /controls[0]/lighting[0]/landing-lights[0]
  125.80 [POPU]:nasal      ERROR: Cannot add listener to tied property /controls[0]/lighting[0]/strobe[0]
  235.40 [ALRT]:nasal      Starter on
  237.90 [ALRT]:nasal      Hobbs system started
  237.95 [ALRT]:nasal      Starter off
  242.93 [ALRT]:nasal      Primer reset to 0
  306.77 [INFO]:OSG        
  306.78 [WARN]:OSG        osgDB ac3d reader: detected surface with less than 3 vertices!
  306.78 [WARN]:OSG        osgDB ac3d reader: detected surface with less than 3 vertices!
  306.78 [WARN]:OSG        osgDB ac3d reader: detected surface with less than 3 vertices!
  306.78 [WARN]:OSG        osgDB ac3d reader: detected surface with less than 3 vertices!
  306.78 [WARN]:OSG        osgDB ac3d reader: detected surface with less than 3 vertices!
  306.78 [WARN]:OSG        osgDB ac3d reader: detected surface with less than 3 vertices!
  306.78 [WARN]:OSG        osgDB ac3d reader: detected surface with less than 3 vertices!
  306.78 [WARN]:OSG        osgDB ac3d reader: detected surface with less than 3 vertices!
  306.78 [WARN]:OSG        osgDB ac3d reader: detected surface with less than 3 vertices!
  306.78 [WARN]:OSG        osgDB ac3d reader: detected surface with less than 3 vertices!
  306.78 [WARN]:OSG        osgDB ac3d reader: detected surface with less than 3 vertices!
  306.78 [WARN]:OSG        osgDB ac3d reader: detected surface with less than 3 vertices!
  306.78 [WARN]:OSG        osgDB ac3d reader: detected surface with less than 3 vertices!
  306.78 [WARN]:OSG        osgDB ac3d reader: detected surface with less than 3 vertices!
  306.78 [WARN]:OSG        osgDB ac3d reader: detected surface with less than 3 vertices!
  306.78 [WARN]:OSG        osgDB ac3d reader: detected surface with less than 3 vertices!
  309.63 [WARN]:OSG        
  309.63 [ALRT]:OSG        osgDB ac3d reader: could not find texture "I:/dev/flightgear-models/flightgear/aircraft/F-15/Models/Liveries/livery.AF80-0007.jpg"
  309.63 [ALRT]:OSG        osgDB ac3d reader: could not find texture "livery.AF80-0007.jpg"
  320.82 [ALRT]:nasal      Hobbs system stopped
  339.06 [ALRT]:nasal      Starter on
  341.23 [ALRT]:nasal      Hobbs system started
  341.27 [ALRT]:nasal      Starter off
  346.27 [ALRT]:nasal      Primer reset to 0
  625.48 [ALRT]:OSG        osgDB ac3d reader: could not find texture "I:/dev/flightgear-models/flightgear/aircraft/F-15/Models/Liveries/livery.AF80-0007.jpg"
  625.48 [ALRT]:OSG        osgDB ac3d reader: could not find texture "livery.AF80-0007.jpg"
```
**Tests:**
1- Default: 
Engine start and takeoff, no problem.

2- Amphibious (starting from Default on the tarmac):
Appears pontoons on the tarmac with the amphibious gear **UP**. No FG crash.
Amphibious gear DOWN: no problem.
Amphibious gear UP again (still on the tarmac): no problem.
Amphibious gear DOWN: no problem, takeoff and fly, landing on water.

With these tests, no FG crash at all.

**Comment by dany93** [comment]
Should I have tested 'severely crashing the amphibious gears and the pontoons'?

**Comment by gilbertohasnofb** [comment]
@dany93 if you are satisfied the issue has been solved then you can merge this PR.
@wlbragg since the new release is out already, I don't think there is the need to cherry-pick it. Unfortunately it will be present until the next release I am afraid :cry:

**Comment by dany93** [comment]
Not completely satisfied (see my comments).

> Appears on the tarmac with the amphibious gear down (= normal), but Autostart makes amphibious gear UP. (go back in 'up' position)
> 
> No FG crash, but "Repair" makes it break again on the tarmac when the gears are recovering the down position.
> 

I'd prefer @wlbragg's opinion on these.

**Comment by wlbragg** [comment]
>Appears on the tarmac with the amphibious gear down (= normal), but Autostart makes amphibious gear UP. (go back in 'up' position)

That obviously shouldn't happen, I'll correct that.

>No FG crash, but "Repair" makes it break again on the tarmac when the gears are recovering the down position.

I noticed the same, I will put that on the same "repair" timer we use for gear change outs that eliminated the damage when gear configurations were changed.

>Should I have tested 'severely crashing the amphibious gears and the pontoons'?

Yes, what you should see is...
1) "damaged", gear causes no change to gear control or operations or contact points. I think all that happens is they will slowly fill with water if on the water.

2) "broken", causes land/water sensor to indicate "water" (blue lights), gear retracts permanently and pontoons are visibly damaged, contact points change to pontoon damage position, panel gear control switch operates but exterior pontoon gear mechanism will not move (hydraulics is considered broken).

**Comment by wlbragg** [comment]
@dany93 all done I think. This should cleanup the issues you had.

I am really confident of the major bug of crashing the simulator being repaired. I know exactly what it was and eliminated the possibility.
The issue was an "infinite" loop caused by two different jsbsim functions trying to control the gear contact positions at the same time.

**Comment by dany93** [comment]
1- An issue remains.
At least after a severe crash (pontoons + gears), (or pontoons + gears + a wing), "Repair" makes it break again on the tarmac when the gears are recovering the down position.
I'm surprised that it worked well for you...

2- I don't know how to get only "damaged" (possibly difficult to control the crash severity by flying).
Neither how to check this state in the Internal Properties.
Neither how to force, by "set" this state in the Internal Properties.
I guess this is not the most important.

**Comment by dany93** [comment]
> "Repair" makes it break again on the tarmac when the gears are recovering the down position.

I'm wondering if it's only a timer problem. I found that the pontoon gears were very hard to break (by hard landing), while the gear extension at "Repair" seems smooth and slow. At least seen from the 3D animation.

**Comment by wlbragg** [comment]
>I found that the pontoon gears were very hard to break (by hard landing),

Hum, I don't think we have any logic for amphibious gear damage, only the pontoons and the conventional gear. That would explain this. I guess I should add some damage logic to the amphibious gears same as we do for the conventional gears.

I change the damage code so regardless if you damage or break the pontoons the hydraulics quits working. In both events the gear is broken visually so I think it is appropriate. 

I will add amphibious gear damage logic as a stand alone damage event. So technically you could get gear damage and not pontoon damage, but because any form of pontoon damage, (damage or broken), visually skews the gear, I think I will use pontoon damage as another input besides forces to gear damage.

I was able to reproduce the breakage on repair after severe damage. I changed the timer time for disabling damage during gear retraction and extension, let me know if that works for you, it did for me.

The pontoon "damaged" logic can be manually changed in /fdm/jsbsim/pontoon-damage
0=non damage
1=broken
2=damaged

I'll push it to repo as soon as I get it finished.

**Comment by wlbragg** [comment]
@onox @dany93 

I think we may have changed the gear coeff somewhere along the line and not updated the damage calculations, see below...

~~~
        <!--
            Numbers MUST be the same coefficients as spring_coeff and
            damping_coeff in the FDM for nose and main gear!
        -->

        <fcs_function name="damage/force-nose-gear">
            <function>
                <sum>
                    <product>
                        <value>1800</value><!-- spring coefficient -->
                        <property>gear/unit[0]/compression-ft</property>
                    </product>
                    <product>
                        <value>600</value><!-- damping coefficient -->
                        <property>gear/unit[0]/compression-velocity-fps</property>
                    </product>
                </sum>
            </function>
        </fcs_function>

        <fcs_function name="damage/force-left-gear">
            <function>
                <sum>
                    <product>
                        <value>5400</value><!-- spring coefficient -->
                        <property>gear/unit[1]/compression-ft</property>
                    </product>
                    <product>
                        <value>400</value><!-- damping coefficient -->
                        <property>gear/unit[1]/compression-velocity-fps</property>
                    </product>
                </sum>
            </function>
        </fcs_function>
~~~
I think the above should read
3600 and 1200
5400 and 1800
~~~
        <contact type="BOGEY" name="NOSE">
            <location unit="IN">
                <x> -6.8 </x>
                <y> 0 </y>
                <z> -20.3 </z>
            </location>
            <static_friction> 0.8 </static_friction>
            <dynamic_friction> 0.5 </dynamic_friction>
            <rolling_friction> 0.02 </rolling_friction>
            <spring_coeff unit="LBS/FT"> 3600 </spring_coeff>
            <damping_coeff unit="LBS/FT/SEC"> 1200 </damping_coeff>
            <max_steer unit="DEG"> 30 </max_steer> <!-- limited to 10 deg NWS, but can turn up to 30 with side force -->
            <brake_group> NONE </brake_group>
            <retractable>0</retractable>
        </contact>
        <contact type="BOGEY" name="LEFT_MAIN">
            <location unit="IN">
                <x> 58.2 </x>
                <y> -43 </y>
                <z> -15.3 </z>
            </location>
            <static_friction> 0.8 </static_friction>
            <dynamic_friction> 0.5 </dynamic_friction>
            <rolling_friction> 0.02 </rolling_friction>
            <spring_coeff unit="LBS/FT"> 5400 </spring_coeff>
            <damping_coeff unit="LBS/FT/SEC"> 1800 </damping_coeff>
            <max_steer unit="DEG"> 0.0 </max_steer>
            <brake_group> LEFT </brake_group>
            <retractable>0</retractable>
        </contact>
~~~
Anyone care to try to verify this?

**Comment by wlbragg** [comment]
Hum, I'm not understanding this completely yet?
According to below, amphibious gear is accounted for, at least partially, in the damage logic (19, 20, 21 and 22). But isn't a switch live action as in only as the gear is compressed to equal the condition (make the condition true). Somewhere it has to throw a permanent flag that says something got broke.
~~~
    <channel name="pontoon-damage">

        <!-- Left pontoon damage -->
        <switch name="left-pontoon-damage">
            <output>pontoon-damage/left-pontoon</output>
            <default value="pontoon-damage/left-pontoon"/>

            <!-- No damage -->
            <test logic="OR" value="0">
                settings/damage EQ 0
                damage/repairing EQ 1
                simulation/sim-time-sec LT 0.25
            </test>
            <test logic="AND" value="0">
                bushkit NE 3
                bushkit NE 4
            </test>

            <!-- ================================================================== -->
            <!-- Broken                                                             -->
            <!-- ================================================================== -->

            <test logic="OR" value="1">
                contact/unit[13]/compression-ft GT 0.95
                contact/unit[15]/compression-ft GT 0.95
                contact/unit[17]/compression-ft GT 0.95
                gear/unit[19]/compression-ft GT 0.95
                gear/unit[21]/compression-ft GT 0.95
                pontoon-damage/left-pontoon EQ 1
            </test>

            <!-- ================================================================== -->
            <!-- Damaged                                                            -->
            <!-- ================================================================== -->

            <test logic="OR" value="2">
                contact/unit[13]/compression-ft GT 0.75
                contact/unit[15]/compression-ft GT 0.75
                contact/unit[17]/compression-ft GT 0.75
                gear/unit[19]/compression-ft GT 0.75
                gear/unit[21]/compression-ft GT 0.75
            </test>
        </switch>
~~~

**Comment by wlbragg** [comment]
Unless maybe
pontoon-damage/left-pontoon EQ 1 stays that way until or unless the following condition is met...
~~~
<!-- No damage -->
            <test logic="OR" value="0">
                settings/damage EQ 0
                damage/repairing EQ 1
                simulation/sim-time-sec LT 0.25
            </test>
~~~

**Comment by wlbragg** [comment]
Something else, was the use of "AND" in a switch not working, it really equates to OR? or was that a different jsbsim expression?
~~~
<!-- No damage -->
            <test logic="OR" value="0">
                settings/damage EQ 0
                damage/repairing EQ 1
                simulation/sim-time-sec LT 0.25
            </test>

            <!-- [1] used to guess required force -->
            <test logic="AND" value="1">
                damage/force-right-gear GT 6500.0
                gear/unit[2]/compression-ft GT 0.8
            </test>

            <!-- Side force on right gear -->
            <test logic="AND" value="1">
                forces/fby-gear-lbs LT -1500.0
                gear/unit[2]/compression-ft GT 0.23
            </test>
~~~

**Comment by wlbragg** [comment]
@dany93 
What I ended up doing is extending the repair timer "no damage" flag and now use it for repairing and gear retraction and extension. I also added some logic to catch compression forces for the amphibious gear and if it exceeds a damage threshold I use it for another condition for pontoon damage.
I think this gets everything accounted for.
The only thing I am still questioning is if I need to to change the damage coeff for the regular gear to match the gear coeff as stated in the comment. See https://github.com/c172p-team/c172p/pull/1289#issuecomment-516582789

**Comment by dany93** [comment]
The gear breakage issue at "Repair" is solved.
(I think that was the more urgent)

The other subjects will be harder and longer to respond.

**Comment by dany93** [comment]
> Something else, was the use of "AND" in a switch not working, it really equates to OR? or was that a different jsbsim expression?

If I understand your question well, you are not far but not right.

I guess that you have this in mind
[Regression: switch statement no longer allows use of and and or](https://github.com/JSBSim-Team/jsbsim/issues/181)
[Problem with nested tests in switches](https://github.com/JSBSim-Team/jsbsim/issues/176)
> `Actually any tag within a <test> statement is interpreted as <test logic="AND">: you could have used <smuglob> instead of <and> and JSBSim would have interpreted <smuglob> as <test logic="AND"> nonetheless.`
> 
The important is `within a <test>`.
Every `<test>` taken as a whole can be stated as` logic="AND"` or `logic="OR"`. But not inside.

Although this is not completely closed
https://sourceforge.net/p/flightgear/mailman/message/36645157/

Nested tests are allowed.

**Comment by wlbragg** [comment]
>Something else, was the use of "AND" in a switch not working, it really equates to OR? or was that a different jsbsim expression?

Ah, that's right, thanks for looking that up and refreshing my memory.

OK then, i think the only outstanding potential issue is if we should change the damage coeff for the regular gear to match the gear coeff as stated in the comment. See https://github.com/c172p-team/c172p/pull/1289#issuecomment-516582789

**Comment by wlbragg** [comment]
@dany93  @legoboyvdlp @gilbertohasnofb 
We have the opportunity to get this in the 2019.1 release if we get it merged ASAP.
Thanks to all the testing and feedback I am confident enough that this is fixed. There is still a question about the coeff matching in the damage logic, but that is a small thing that I am not as concerned about, I don't want to change it without understanding why it no longer matches. Maybe it was changed for a reason?
SO with that said I am going to merge this and ping James. He said he would re-sync the entire 2019.1 release branch.

**Comment by dany93** [comment]
> I think the above should read
> 
> 3600 and 1200
> not 1800 and 600
> 
> 5400 and 1800
> not 5400 and 400


You are right.

This has been changed for some reason, and it led to this inconsistency.
The current values in the FDM
```
3600 and 1200
5400 and 1800
```
are correct IMO. These are the initial values.

However, a few people complained that the gears were too easy to break, and I softened the coefficients (changing them to be consistent in the FDM and the damage file).

Later on, a bug in JSBSim was discovered which made the aircraft pitch up and down on the runway with an accurate crosswind (very unlikely, noticed by nobody except us).
[Pitch oscillations at rest, Brakes "ON", with pure crosswind](https://github.com/JSBSim-Team/jsbsim/issues/89)
This sometimes broke the nose gear. The nose gear breaking was solved by restoring the FDM coefficients.

Still later on, the JSBSim bug was not solved, but Bertrand Coconnier proposed a circumventing (a small change to be made, not done yet, in the C172 FDM).

The current inconsistency is that the coefficients in the damage file were not changed to be in accordance. And I'm afraid it will be a difficult compromise because restoring them to be consistent in the damage file:
```
3600 and 1200
5400 and 1800
```
(correct values, IMO)
will probably bring again the previous complaints.

I tried to go back in time to remind this story, I intended (I still intend) to write it for your understanding, but it's quite long and intricate to do.

I hope that this not detailed summary is correct.

**Comment by wlbragg** [comment]
OK, so let's revisit this and we can make an issue to resolve it one way or another. I will make the issue after I am done with this last emergency PR for the amphibious gear.
It will also require a new issue to resolve a newly created (minor) issue.

**Pull request merged**
