### PR TITLE
New Aero Tech LC-2 digital clock

### LINKED ISSUE #1124: Add Digital Clock
image

image

image

The POH of the C172P that I have has a description of a digital clock: how would you feel about replacing our analog clock with this one? It seems to be designed to fit precisely in the same "hole" as the analog clock.

image
image

image

image
image

### PR DESCRIPTION
**Pull request by wlbragg**
Fixes #1124

Replaced PR #1141 

:warning::warning::warning:
PLEASE  MERGE THIS BEFORE Correct light maps on instrument cases #1186
 :warning::warning::warning:

### CODE REVIEW

**Comment by wlbragg** [comment]
I don't think I did this right, how do I push my changes to @legoboyvdlp PR branch, or did I?

**Comment by wlbragg** [comment]
It looks like I grabbed @legoboyvdlp PR and made a new one from it and my additions.

**Comment by legoboyvdlp** [comment]
I'll base my branch off this and push my nasal changes when I do then to this, if that's OK?

**Comment by gilbertohasnofb** [comment]
@wlbragg I think the issue is that @legoboyvdlp used to work on his clone up to now. But since he is now a member of the repo, the best approach would be for either you or him to open a new branch in our repo and both contribute directly to it. @legoboyvdlp you have a couple of PRs opened, see how you want to proceed with them, whether it would be easier to reopen them as branches in our common repo or just go along with your clone for that work. Also, keep in mind that when contributing with other developers in a same branch, you need to constantly do a `git pull`. It's also good if you inform the other developers if you are about to push and when your commit has gone through. This way we can avoid those ugly merge commit messages that happen once in a while.

**Comment by legoboyvdlp** [comment]
I'll push from now on to legoboyvdlp-issue-1124 branch on c172pteam/c172p 😉

**Comment by onox** [comment]
You can push your branch to `issue-1124` with `git push -u origin
issue-1124` where origin is our repository (assuming you have adjusted your
remotes).

**Comment by gilbertohasnofb** [comment]
@onox I think that @wlbragg created a branch named `legoboyvdlp-issue-1124` instead of `issue-1124`, so if lego pushes to `issue-1124` he will be pushing his work to a different branch which is not part of this PR.

**Comment by wlbragg** [comment]
Cool, so @legoboyvdip is this ready to merge as far as you are concerned?

If so @gilbertohasnofb can you wait until i push light maps?

**Comment by legoboyvdlp** [comment]
Yep, though it would be good if @gilbertohasnofb could test.

**Comment by wlbragg** [comment]
>Yep, though it would be good if @gilbertohasnofb could test.

I agree, @gilbertohasnofb when your done testing and satisfied it's all correct. Go ahead and merge this. I am going to make a new PR and issue for the light map changes to all the instruments as I need to base it off of master and the latest light maps we are using.

**Comment by gilbertohasnofb** [comment]
I will test this tomorrow, I'm literally seating in a 777 about to take off.

**Comment by wlbragg** [comment]
@gilbertohasnofb Woo, hoo, have a safe, fun flight and trip!

**Comment by wlbragg** [comment]
@gilbertohasnofb 

:warning::warning::warning: DO NOT MERGE THIS :warning::warning::warning:

I have to make some light map and other adjustments after you merge "Correct light maps on instrument cases #1186"

**Comment by wlbragg** [comment]
@gilbertohasnofb 

:warning::warning::warning:
PLEASE  MERGE THIS BEFORE Correct light maps on instrument cases #1186
 :warning::warning::warning:

**Comment by gilbertohasnofb** [comment]
Very nice work. @legoboyvdlp thanks for implementing this.

**Comment by legoboyvdlp** [comment]
Thank you! Do you usually delete branches post merging?

**Comment by gilbertohasnofb** [comment]
@legoboyvdlp Yes, we should delete branches if no further work will be done on them (which is normally the case since, in theory, the branch should completely solve all issues listed). Sometimes we do forget to delete them (just like I did) but it's always good to close them as to keep the branch list small.

**Pull request merged**
