### PR TITLE
Repair aircraft at the start of each tutorial

### PR DESCRIPTION
**Pull request by legoboyvdlp**
Fixes the ticket just opened on sourceforge.

### CODE REVIEW

**Comment by wlbragg** [comment]
@legoboyvdlp does this fix the stuck brakes?

**Comment by legoboyvdlp** [comment]
I didn't see stuck brakes?

This is about the problem where a user left the radios on too long and drained the battery entirely during a tutorial. This now does a full repair at the start of each tutorial.

**Comment by wlbragg** [comment]
Ah, ok let me see what effect if any this has on the other issue with the parking brake. Thanks for fixing this issue. I'll merge as soon as I test it.

**Comment by wlbragg** [comment]
Nice, this actually fixed the brake issue for tutorial relocations. The only brake issue now is when doing and Airport relocation. Thanks @legoboyvdlp

**Comment by onox** [comment]
@legoboyvdlp I see a lot of repeated code. You could put it all in one function (something like `c172p.repair_aircraft_for_tutorial()`) so you only have to modify 1 location if you ever need to modify something.

**Pull request merged**
